"""Single source for component documentation. build_docs.py turns it into
*.docs.md, *.examples.md, *.tokens.json and MANIFEST.json.

Every field is required unless marked optional. Keep text in Spanish (docs) and
code in English (API)."""

FIGMA_FILE = "https://www.figma.com/design/GZRi3cvtWVfu0MTxPvPEcY/Design-System"

P = lambda name, type_, default, required, desc: dict(name=name, type=type_, default=default, required=required, desc=desc)

SPECS = [
    # ------------------------------------------------------------------ ATOMS
    dict(
        name="Button", category="atom", status="stable", figma="8:425",
        purpose="Dispara una acción en la vista actual.",
        when=["Enviar un formulario, confirmar o cancelar una decisión.", "Abrir un flujo (Send new submission, View & Download).", "Una sola variante primary por vista: la acción principal."],
        when_not=["Para navegar a otra URL: usar un enlace (`as=\"a\"`) o `ListItem` type=navigation.", "Para alternar un ajuste: usar `Switch`.", "Para filtros seleccionables: usar `TagChip`."],
        anatomy=["Contenedor (fondo, borde, radio `button.radius`)", "Icono inicial opcional (`Icon`)", "Label (estilo `typography.button`)", "Icono final opcional (`Icon`)"],
        props=[P("children", "ReactNode", "—", True, "Texto visible del botón. Verbo + objeto: 'Send request'."),
               P("variant", "'primary' | 'secondary' | 'ghost' | 'danger'", "'primary'", False, "Jerarquía visual de la acción."),
               P("size", "'small' | 'medium' | 'large'", "'medium'", False, "Altura 32 / 44 / 52 px."),
               P("leadingIcon", "IconName", "—", False, "Icono antes del texto."),
               P("trailingIcon", "IconName", "—", False, "Icono después del texto."),
               P("isDisabled", "boolean", "false", False, "Deshabilita el botón (aria-disabled)."),
               P("isLoading", "boolean", "false", False, "Sustituye el icono inicial por Spinner y bloquea clics."),
               P("isFullWidth", "boolean", "false", False, "Ocupa el ancho del contenedor (formularios)."),
               P("type", "'button' | 'submit' | 'reset'", "'button'", False, "Tipo HTML."),
               P("onPress", "() => void", "—", False, "Acción al pulsar (click, Enter, Espacio).")],
        variants={"variant": ["primary", "secondary", "ghost", "danger"], "size": ["small", "medium", "large"]},
        states=["default", "hover", "pressed", "focus", "disabled", "loading"],
        tokens=["button.primary.*", "button.secondary.*", "button.ghost.*", "button.danger.*", "button.disabled.*", "button.radius", "button.gap", "button.padding-horizontal.*", "button.typography", "elevation.focus", "size.layout.control-height*"],
        interaction=["Hover y pressed cambian el fondo con `motion.transition-fast`.", "Enter y Espacio disparan `onPress`.", "En loading el ancho no cambia y `aria-busy=true`."],
        a11y=["Elemento `<button>` nativo; si navega, `<a>` con el mismo estilo.", "Foco visible: borde 2px `color.border.focus` por fuera.", "Botones solo con icono requieren `aria-label` y un `Tooltip`.", "Contraste del texto ≥ 4.5:1 en todas las variantes (por eso primary usa ocean 700→600).", "Disabled usa `aria-disabled` para seguir siendo descubrible por lector de pantalla."],
        composition=["Máximo un primary por vista o por Modal.", "En un grupo, la acción principal va a la derecha (Modal) o arriba y a ancho completo (FormSection).", "No anidar elementos interactivos dentro."],
        antipatterns=["Dos botones primary en la misma vista.", "Cambiar colores con estilos sueltos en lugar de `variant`.", "Usar `ghost` para acciones destructivas.", "Texto genérico ('Click here', 'OK')."],
        deps=["Icon", "Spinner"],
        example='<Button variant="primary" leadingIcon="eye" onPress={openReview}>View & Download</Button>',
        examples_bad='<Button style={{ background: "#3b8eaa" }}>OK</Button>',
    ),
    dict(
        name="Icon", category="atom", status="stable", figma="7:6",
        purpose="Muestra un pictograma de línea del set de Alora.",
        when=["Reforzar el significado de un texto (botones, tags, navegación).", "Botones solo con icono cuando el espacio es mínimo y el significado universal (cerrar, buscar)."],
        when_not=["Como única forma de comunicar un estado: añadir texto.", "Para ilustraciones o logotipos: usar imágenes o el Logo del Sidebar."],
        anatomy=["Caja 24×24", "Trazo 2px con remates redondeados (estilo Lucide)"],
        props=[P("name", "IconName", "—", True, "home, list, user, users, calendar, play-circle, bell, eye, clock, check, close, chevron-right, chevron-left, search, info, plus, upload, log-in, log-out, edit, repeat, warning, check-circle, star, trending-up, mail, lock, trash, video."),
               P("size", "'xs' | 'sm' | 'md' | 'lg' | 'xl'", "'lg'", False, "12 / 16 / 20 / 24 / 32 px (`size.icon.*`)."),
               P("tone", "'primary' | 'secondary' | 'brand' | 'inherit'", "'inherit'", False, "Color `color.icon.*`; inherit usa currentColor."),
               P("label", "string", "—", False, "Si se indica, el icono es significativo (`role=img` + `aria-label`). Si no, `aria-hidden`.")],
        variants={"size": ["xs", "sm", "md", "lg", "xl"], "tone": ["primary", "secondary", "brand", "inherit"]},
        states=["—"],
        tokens=["color.icon.primary", "color.icon.secondary", "color.icon.brand", "size.icon.*"],
        interaction=["No es interactivo por sí mismo."],
        a11y=["Decorativo por defecto (`aria-hidden=true`).", "Con `label` pasa a `role=img`.", "Contraste ≥ 3:1 con el fondo cuando transmite información."],
        composition=["Dentro de Button, Tag, NavigationItem, Notification, Input.", "El color lo decide el componente padre (`tone=inherit`)."],
        antipatterns=["Iconos de otras librerías mezclados con el set.", "Cambiar el grosor del trazo.", "Icono sin texto ni aria-label en un control."],
        deps=[],
        example='<Icon name="clock" size="sm" tone="inherit" />',
        examples_bad='<img src="clock.png" />',
    ),
    dict(
        name="Label", category="atom", status="stable", figma="9:11",
        purpose="Nombra un control de formulario.",
        when=["Encima de Input, Textarea o a la derecha de Checkbox, Radio y Switch."],
        when_not=["Como título de sección: usar Heading.", "Como texto de ayuda: usar Text dentro de FormField."],
        anatomy=["Texto (`typography.label`)", "Marca de requerido opcional (*)"],
        props=[P("children", "ReactNode", "—", True, "Nombre del campo."),
               P("htmlFor", "string", "—", True, "id del control asociado."),
               P("isRequired", "boolean", "false", False, "Añade * y requiere aria-required en el control."),
               P("isDisabled", "boolean", "false", False, "Atenúa el label (`color.text.disabled`).")],
        variants={}, states=["default", "disabled"],
        tokens=["typography.label", "color.text.primary", "color.text.disabled", "color.feedback.danger.foreground"],
        interaction=["Clic en el label enfoca o activa el control."],
        a11y=["`<label for>` nativo.", "El asterisco es decorativo (`aria-hidden`); la obligatoriedad se comunica con `aria-required`."],
        composition=["Solo dentro de FormField o junto a Checkbox / Radio / Switch."],
        antipatterns=["Usar el placeholder como label.", "Labels en mayúsculas: el estilo ya define la tipografía."],
        deps=[],
        example='<Label htmlFor="email" isRequired>Email</Label>',
        examples_bad='<span style={{ fontWeight: 600 }}>Email</span>',
    ),
    dict(
        name="Text", category="atom", status="stable", figma="9:65",
        purpose="Muestra texto de lectura y metadatos con un rol tipográfico y un tono semántico.",
        when=["Párrafos, descripciones, metadatos, fechas y overlines."],
        when_not=["Títulos: usar Heading.", "Etiquetas de formulario: usar Label."],
        anatomy=["Texto"],
        props=[P("children", "ReactNode", "—", True, "Contenido."),
               P("role", "'body-large' | 'body-medium' | 'body-small' | 'caption' | 'overline'", "'body-medium'", False, "Estilo tipográfico (`typography.*`)."),
               P("tone", "'primary' | 'secondary' | 'tertiary' | 'brand' | 'danger'", "'primary'", False, "Color semántico."),
               P("as", "'p' | 'span' | 'div' | 'dd' | 'dt'", "'p'", False, "Elemento HTML.")],
        variants={"role": ["body-large", "body-medium", "body-small", "caption", "overline"], "tone": ["primary", "secondary", "tertiary", "brand", "danger"]},
        states=["—"],
        tokens=["typography.body-*", "typography.caption", "typography.overline", "color.text.*", "color.feedback.danger.foreground"],
        interaction=["No interactivo."],
        a11y=["`tertiary` cumple 4.5:1 sobre surface-raised, pero no se usa para información crítica.", "`overline` se escribe en mayúsculas en el contenido; no usar text-transform para siglas."],
        composition=["Libre dentro de moléculas y organismos."],
        antipatterns=["Combinar tamaño y peso sueltos en vez de `role`.", "Usar `brand` para texto no enlazable de forma masiva."],
        deps=[],
        example='<Text role="body-small" tone="tertiary">Submitted 31 ago 2026, 18:01</Text>',
        examples_bad='<p style={{ fontSize: 12, color: "#4d6e87" }}>Submitted…</p>',
    ),
    dict(
        name="Heading", category="atom", status="stable", figma="9:77",
        purpose="Titula una vista, sección o tarjeta respetando la jerarquía del documento.",
        when=["Saludo de la vista (display, h1).", "Títulos de sección (medium, h2) y de tarjeta (small, h3)."],
        when_not=["Para destacar texto dentro de un párrafo: usar Text."],
        anatomy=["Texto (`typography.display` o `typography.heading-*`)"],
        props=[P("children", "ReactNode", "—", True, "Texto del título."),
               P("level", "'display' | 'large' | 'medium' | 'small'", "'medium'", False, "Estilo visual."),
               P("as", "'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6'", "según level", False, "Nivel semántico; no saltar niveles.")],
        variants={"level": ["display", "large", "medium", "small"]}, states=["—"],
        tokens=["typography.display", "typography.heading-large", "typography.heading-medium", "typography.heading-small", "color.text.primary"],
        interaction=["No interactivo."],
        a11y=["Un solo h1 por vista.", "El orden de niveles refleja la estructura, no el tamaño."],
        composition=["PageHeader usa display; DataList usa medium; SubmissionCard usa small."],
        antipatterns=["Usar Heading para texto en negrita sin función de título.", "Saltar de h1 a h4."],
        deps=[],
        example='<Heading level="display" as="h1">Welcome, Alejandro</Heading>',
        examples_bad='<div className="big-bold">Welcome</div>',
    ),
    dict(
        name="Input", category="atom", status="stable", figma="9:161",
        purpose="Recoge una línea de texto.",
        when=["Email, contraseña, nombre, búsqueda (a través de SearchField)."],
        when_not=["Texto largo: usar Textarea.", "Opciones cerradas: usar Radio o un Select (planificado)."],
        anatomy=["Contenedor (fondo `input.background`, borde `input.border.*`, radio `input.radius`)", "Icono inicial opcional", "Valor o placeholder", "Icono final opcional (mostrar contraseña)"],
        props=[P("id", "string", "—", True, "Para asociar Label y mensajes."),
               P("value", "string", "—", False, "Valor controlado."),
               P("placeholder", "string", "—", False, "Ejemplo de formato, nunca sustituye al Label."),
               P("type", "'text' | 'email' | 'password' | 'search' | 'tel'", "'text'", False, "Tipo HTML."),
               P("leadingIcon", "IconName", "—", False, "Icono antes del valor."),
               P("trailingIcon", "IconName", "—", False, "Icono o acción después del valor."),
               P("hasError", "boolean", "false", False, "Borde de error y `aria-invalid`."),
               P("isDisabled", "boolean", "false", False, "Deshabilitado."),
               P("onChange", "(value: string) => void", "—", False, "Cambio de valor.")],
        variants={}, states=["default", "hover", "focus", "error", "disabled", "filled"],
        tokens=["input.background", "input.foreground", "input.placeholder", "input.border.default", "input.border.hover", "input.border.focus", "input.border.error", "input.radius", "input.padding-horizontal", "input.typography", "size.layout.control-height", "size.border.focus"],
        interaction=["Focus: borde 2px `input.border.focus`.", "Error: borde 2px `input.border.error`; el mensaje lo pinta FormField."],
        a11y=["Siempre con Label asociado (lo garantiza FormField).", "`aria-invalid` y `aria-describedby` hacia ayuda y error.", "`autocomplete` correcto (email, current-password)."],
        composition=["Usar dentro de FormField. Fuera de un formulario, solo a través de SearchField."],
        antipatterns=["Placeholder como única etiqueta.", "Bordes rojos sin mensaje de error."],
        deps=["Icon"],
        example='<Input id="email" type="email" value={email} onChange={setEmail} />',
        examples_bad='<input style={{ border: "1px solid red" }} placeholder="Email" />',
    ),
    dict(
        name="Textarea", category="atom", status="stable", figma="9:177",
        purpose="Recoge texto de varias líneas.",
        when=["Nota del surfer al coach, motivo de cambio de coach."],
        when_not=["Valores de una línea: usar Input."],
        anatomy=["Contenedor (tokens `input.*`)", "Valor o placeholder", "Contador opcional"],
        props=[P("id", "string", "—", True, "Para asociar Label."),
               P("value", "string", "—", False, "Valor controlado."),
               P("maxLength", "number", "—", False, "Muestra contador 'n / max'."),
               P("rows", "number", "4", False, "Altura inicial."),
               P("hasError", "boolean", "false", False, "Estado de error."),
               P("isDisabled", "boolean", "false", False, "Deshabilitado."),
               P("onChange", "(value: string) => void", "—", False, "Cambio de valor.")],
        variants={}, states=["default", "focus", "error", "disabled"],
        tokens=["input.*", "typography.body-medium", "typography.caption", "color.text.tertiary"],
        interaction=["Crece con el contenido hasta 8 filas y luego hace scroll."],
        a11y=["Contador enlazado con `aria-describedby` y anunciado al llegar al límite."],
        composition=["Dentro de FormField o del slot Content de Modal."],
        antipatterns=["Usarlo para un único dato corto."],
        deps=[],
        example='<Textarea id="note" maxLength={280} value={note} onChange={setNote} />',
        examples_bad='<textarea style={{ height: 112 }} />',
    ),
    dict(
        name="Checkbox", category="atom", status="stable", figma="12:44",
        purpose="Permite marcar una o varias opciones independientes.",
        when=["Aceptar términos, 'Remember me', seleccionar varios elementos."],
        when_not=["Opción única entre varias: Radio.", "Ajuste con efecto inmediato: Switch."],
        anatomy=["Caja 18×18 (`checkbox.radius`)", "Marca check o guion (indeterminate)", "Label"],
        props=[P("label", "ReactNode", "—", True, "Texto visible."),
               P("isChecked", "boolean | 'indeterminate'", "false", False, "Estado."),
               P("isDisabled", "boolean", "false", False, "Deshabilitado."),
               P("onChange", "(checked: boolean) => void", "—", False, "Cambio.")],
        variants={"checked": ["false", "true", "indeterminate"]}, states=["default", "focus", "disabled"],
        tokens=["checkbox.border", "checkbox.background-checked", "checkbox.foreground-checked", "checkbox.radius", "color.border.focus"],
        interaction=["Clic en caja o label alterna.", "Espacio alterna con foco."],
        a11y=["`<input type=checkbox>` nativo.", "Indeterminate con `aria-checked=mixed`.", "Área clicable ≥ 24×24 incluyendo label."],
        composition=["Grupos dentro de `<fieldset>` con `<legend>`."],
        antipatterns=["Checkbox que dispara una acción inmediata.", "Sin label visible."],
        deps=["Icon", "Label"],
        example='<Checkbox label="Remember me" isChecked={remember} onChange={setRemember} />',
        examples_bad='<div onClick={toggle} className="box" />',
    ),
    dict(
        name="Radio", category="atom", status="stable", figma="12:71",
        purpose="Permite elegir una sola opción dentro de un grupo.",
        when=["2–5 opciones excluyentes visibles (stance Regular/Goofy, nivel)."],
        when_not=["Más de 5 opciones: Select (planificado).", "Opciones múltiples: Checkbox."],
        anatomy=["Círculo 18×18", "Punto interior al seleccionar", "Label"],
        props=[P("label", "ReactNode", "—", True, "Texto visible."),
               P("value", "string", "—", True, "Valor de la opción."),
               P("name", "string", "—", True, "Nombre del grupo."),
               P("isSelected", "boolean", "false", False, "Seleccionado."),
               P("isDisabled", "boolean", "false", False, "Deshabilitado.")],
        variants={"selected": ["false", "true"]}, states=["default", "focus", "disabled"],
        tokens=["radio.border", "radio.border-checked", "radio.dot", "color.border.focus"],
        interaction=["Flechas mueven la selección dentro del grupo."],
        a11y=["`<input type=radio>` en `<fieldset>` con `<legend>` o `role=radiogroup` con nombre."],
        composition=["Siempre en grupo de al menos 2."],
        antipatterns=["Un radio suelto.", "Grupo sin opción por defecto cuando el dato es obligatorio."],
        deps=["Label"],
        example='<Radio name="stance" value="goofy" label="Goofy" isSelected={stance === "goofy"} />',
        examples_bad='<Radio label="Accept terms" />',
    ),
    dict(
        name="Switch", category="atom", status="stable", figma="12:91",
        purpose="Activa o desactiva un ajuste con efecto inmediato.",
        when=["Preferencias que se guardan al instante (notificaciones)."],
        when_not=["Cuando el cambio requiere pulsar Guardar: Checkbox."],
        anatomy=["Pista 36×20 (`switch.radius`)", "Thumb 16×16", "Label"],
        props=[P("label", "ReactNode", "—", True, "Texto visible."),
               P("isOn", "boolean", "false", False, "Estado."),
               P("isDisabled", "boolean", "false", False, "Deshabilitado."),
               P("onChange", "(on: boolean) => void", "—", False, "Cambio.")],
        variants={"on": ["false", "true"]}, states=["default", "disabled"],
        tokens=["switch.track-off", "switch.track-on", "switch.thumb", "switch.radius", "color.border.default"],
        interaction=["El thumb se desplaza con `motion.transition-base`."],
        a11y=["`role=switch` + `aria-checked`.", "El estado no depende solo del color: la posición del thumb cambia."],
        composition=["Listas de ajustes, una por fila."],
        antipatterns=["Switch dentro de un formulario con botón Guardar."],
        deps=["Label"],
        example='<Switch label="Email notifications" isOn={notify} onChange={setNotify} />',
        examples_bad='<Switch label="Accept terms" />',
    ),
    dict(
        name="Avatar", category="atom", status="stable", figma="12:119",
        purpose="Representa a una persona con sus iniciales.",
        when=["Junto al nombre de un surfer o coach (listas, tarjetas, cabecera)."],
        when_not=["Como único identificador de una persona: mostrar siempre el nombre."],
        anatomy=["Círculo (`avatar.radius`)", "Iniciales"],
        props=[P("name", "string", "—", True, "Nombre completo; se calculan las iniciales."),
               P("size", "'small' | 'medium' | 'large'", "'medium'", False, "24 / 32 / 64 px."),
               P("tone", "'brand' | 'elite' | 'progression' | 'neutral'", "'brand'", False, "Color de fondo; los tonos de plan van con Badge de plan.")],
        variants={"size": ["small", "medium", "large"], "tone": ["brand", "elite", "progression", "neutral"]}, states=["—"],
        tokens=["avatar.background", "avatar.foreground", "avatar.radius", "color.plan.*.foreground", "color.text.inverse"],
        interaction=["No interactivo; si abre el perfil, envolver en un enlace con el nombre."],
        a11y=["Iniciales con `aria-hidden`; el nombre visible al lado da el contexto."],
        composition=["ListItem type=person, SubmissionCard, PageHeader."],
        antipatterns=["Comunicar el plan solo con el color del avatar."],
        deps=[],
        example='<Avatar name="Khata Kraiwan" tone="elite" />',
        examples_bad='<div className="circle" style={{ background: "#d97706" }}>K</div>',
    ),
    dict(
        name="Badge", category="atom", status="stable", figma="12:139",
        purpose="Etiqueta no interactiva que muestra un estado o un plan.",
        when=["Estado de un envío (Pending, In review, Review ready, Overdue).", "Plan del surfer (Pay as you go, Elite, Progression)."],
        when_not=["Información con icono o tiempo: Tag.", "Elementos seleccionables o eliminables: TagChip."],
        anatomy=["Contenedor (`badge.radius`, padding `badge.padding-*`)", "Texto en mayúsculas (`typography.overline`)"],
        props=[P("children", "string", "—", True, "Texto del estado."),
               P("tone", "'pending' | 'in-review' | 'review-ready' | 'overdue' | 'neutral' | 'plan-pay-as-you-go' | 'plan-elite' | 'plan-progression'", "'neutral'", False, "Tono semántico.")],
        variants={"tone": ["pending", "in-review", "review-ready", "overdue", "neutral", "plan-pay-as-you-go", "plan-elite", "plan-progression"]}, states=["—"],
        tokens=["badge.radius", "badge.padding-horizontal", "badge.padding-vertical", "badge.typography", "color.status.*", "color.plan.*", "color.feedback.neutral.*"],
        interaction=["No interactivo."],
        a11y=["El texto nombra el estado; el color solo refuerza.", "Contraste ≥ 4.5:1 en todos los tonos."],
        composition=["SubmissionCard (estado y plan), Sidebar futuro (contadores)."],
        antipatterns=["Badge clicable.", "Inventar tonos fuera de la lista."],
        deps=[],
        example='<Badge tone="in-review">In review</Badge>',
        examples_bad='<span style={{ color: "#f5c53a" }}>Pending</span>',
    ),
    dict(
        name="Tag", category="atom", status="stable", figma="12:167",
        purpose="Píldora informativa con icono opcional.",
        when=["Tiempo restante de una revisión, plan destacado, contexto (Surf park)."],
        when_not=["Estados cortos sin icono: Badge.", "Elementos seleccionables o eliminables: TagChip."],
        anatomy=["Contenedor píldora (`tag.radius`)", "Icono opcional", "Texto (`typography.body-small`)"],
        props=[P("children", "ReactNode", "—", True, "Texto."),
               P("tone", "'brand' | 'highlight' | 'warning' | 'danger' | 'neutral'", "'brand'", False, "Tono semántico."),
               P("icon", "IconName", "—", False, "Icono inicial.")],
        variants={"tone": ["brand", "highlight", "warning", "danger", "neutral"]}, states=["—"],
        tokens=["tag.background", "tag.foreground", "tag.border", "tag.radius", "tag.padding-horizontal", "color.background.highlight-subtle", "color.text.highlight", "color.feedback.*"],
        interaction=["No interactivo."],
        a11y=["Si el Tag comunica urgencia (warning/danger), el texto lo dice ('1h 9m left', 'Overdue')."],
        composition=["SubmissionCard (plazo), PageHeader (plan, notificaciones)."],
        antipatterns=["Usar Tag como botón."],
        deps=["Icon"],
        example='<Tag tone="warning" icon="clock">1h 9m left</Tag>',
        examples_bad='<Tag onClick={…}>Filter</Tag>',
    ),
    dict(
        name="Spinner", category="atom", status="stable", figma="12:180",
        purpose="Indica una espera de duración indeterminada.",
        when=["Subida de vídeo, envío de revisión, carga de la cola."],
        when_not=["Progreso medible: barra de progreso (planificado).", "Carga de una vista completa: skeletons (planificado)."],
        anatomy=["Pista circular (`spinner.track`)", "Arco animado (`spinner.indicator`)"],
        props=[P("size", "'small' | 'medium' | 'large'", "'medium'", False, "16 / 24 / 32 px."),
               P("label", "string", "'Loading'", False, "Texto para lectores de pantalla.")],
        variants={"size": ["small", "medium", "large"]}, states=["—"],
        tokens=["spinner.track", "spinner.indicator", "size.border.focus", "motion.duration.slow"],
        interaction=["Rota de forma continua; con `prefers-reduced-motion` pulsa la opacidad."],
        a11y=["`role=status` con `aria-label`.", "Respeta `prefers-reduced-motion`."],
        composition=["Dentro de Button (isLoading) o centrado en un EmptyState de carga."],
        antipatterns=["Varios spinners simultáneos en una vista."],
        deps=[],
        example='<Spinner size="small" label="Uploading video" />',
        examples_bad='<img src="loader.gif" />',
    ),
    dict(
        name="Divider", category="atom", status="stable", figma="12:186",
        purpose="Separa grupos de contenido.",
        when=["Entre el bloque de stats y la lista de envíos; entre filas de lista."],
        when_not=["Para crear espacio: usar tokens `size.space.*`."],
        anatomy=["Línea de 1px (`divider.color`)"],
        props=[P("orientation", "'horizontal' | 'vertical'", "'horizontal'", False, "Dirección."),
               P("isDecorative", "boolean", "true", False, "Si es false, `role=separator`.")],
        variants={"orientation": ["horizontal", "vertical"]}, states=["—"],
        tokens=["divider.color", "size.border.default"],
        interaction=["No interactivo."],
        a11y=["Decorativo por defecto (`aria-hidden`)."],
        composition=["Libre."],
        antipatterns=["Bordes dibujados a mano con otros colores."],
        deps=[],
        example='<Divider />',
        examples_bad='<hr style={{ borderColor: "#333" }} />',
    ),
    dict(
        name="Tooltip", category="atom", status="beta", figma="12:200",
        purpose="Describe brevemente un control al hacer hover o focus.",
        when=["Botones solo con icono, abreviaturas."],
        when_not=["Información esencial o acciones: usar texto visible o Notification."],
        anatomy=["Burbuja (`tooltip.background`, `tooltip.radius`)", "Flecha", "Texto (`typography.body-small`)"],
        props=[P("content", "string", "—", True, "Texto breve (≤ 60 caracteres)."),
               P("placement", "'top' | 'bottom'", "'top'", False, "Posición."),
               P("children", "ReactElement", "—", True, "Elemento disparador enfocable.")],
        variants={"placement": ["top", "bottom"]}, states=["hidden", "visible"],
        tokens=["tooltip.background", "tooltip.foreground", "tooltip.radius", "tooltip.padding", "z-index.tooltip"],
        interaction=["Aparece tras 300ms de hover o al instante con foco; Escape lo cierra."],
        a11y=["`role=tooltip` enlazado con `aria-describedby`.", "No desaparece mientras el puntero está encima (WCAG 1.4.13)."],
        composition=["Envuelve Button icon-only."],
        antipatterns=["Tooltips con enlaces o botones dentro."],
        deps=[],
        example='<Tooltip content="Close"><Button variant="ghost" leadingIcon="close" aria-label="Close" /></Tooltip>',
        examples_bad='<Tooltip content="Your plan renews on 26 sept and you will be charged…">',
    ),
    # -------------------------------------------------------------- MOLECULES
    dict(
        name="FormField", category="molecule", status="stable", figma="13:54",
        purpose="Agrupa Label, Input, texto de ayuda y mensaje de error de un campo.",
        when=["Cualquier campo de formulario (log in, onboarding, perfil)."],
        when_not=["Búsqueda: SearchField."],
        anatomy=["Label", "Input o Textarea", "Texto de ayuda opcional", "Mensaje de error con icono"],
        props=[P("label", "string", "—", True, "Texto del Label."),
               P("id", "string", "—", True, "id del control."),
               P("helperText", "string", "—", False, "Ayuda bajo el campo."),
               P("errorMessage", "string", "—", False, "Si existe, el campo pasa a error."),
               P("isRequired", "boolean", "false", False, "Obligatorio."),
               P("isDisabled", "boolean", "false", False, "Deshabilitado."),
               P("children", "ReactElement<Input | Textarea>", "—", True, "Control.")],
        variants={}, states=["default", "error", "disabled"],
        tokens=["size.space.small", "typography.body-small", "color.text.tertiary", "color.feedback.danger.foreground"],
        interaction=["El error aparece al salir del campo o al enviar, no mientras se escribe."],
        a11y=["Conecta `aria-describedby` con ayuda y error.", "El error se anuncia con `role=alert` la primera vez."],
        composition=["Dentro de FormSection o del slot Content de Modal."],
        antipatterns=["Mostrar ayuda y error a la vez.", "Mensajes de error que no dicen cómo corregir."],
        deps=["Label", "Input", "Textarea", "Text", "Icon"],
        example='<FormField id="email" label="Email" errorMessage={error}>\n  <Input id="email" type="email" />\n</FormField>',
        examples_bad='<Label>Email</Label><Input /><span className="red">Error</span>',
    ),
    dict(
        name="SearchField", category="molecule", status="stable", figma="13:92",
        purpose="Campo de búsqueda con icono y botón de limpiar.",
        when=["Buscar surfers, clips o spots en listas largas."],
        when_not=["Filtros de valores cerrados: TagChip."],
        anatomy=["Input con icono search", "Botón limpiar (visible con texto)"],
        props=[P("value", "string", "—", True, "Texto de búsqueda."),
               P("onChange", "(value: string) => void", "—", True, "Cambio."),
               P("placeholder", "string", "'Search'", False, "Qué se busca: 'Search surfers'."),
               P("onClear", "() => void", "—", False, "Limpia y devuelve el foco.")],
        variants={"filled": ["false", "true"]}, states=["default", "focus"],
        tokens=["input.*", "color.icon.secondary"],
        interaction=["Escape limpia el texto.", "Los resultados se filtran con debounce de 200ms."],
        a11y=["Contenedor `role=search`; Input `type=search` con label oculto.", "El botón limpiar tiene `aria-label=\"Clear search\"`."],
        composition=["Encima de listas (Surfers)."],
        antipatterns=["Búsqueda sin label accesible."],
        deps=["Input", "Icon", "Button"],
        example='<SearchField value={q} onChange={setQ} placeholder="Search surfers" />',
        examples_bad='<Input placeholder="Search…" />',
    ),
    dict(
        name="ListItem", category="molecule", status="stable", figma="13:120",
        purpose="Fila de una lista con tres formatos: persona, definición o navegación.",
        when=["Lista de surfers (person).", "Datos de cuenta (definition).", "Enlaces legales (navigation)."],
        when_not=["Contenido rico con acciones múltiples: SubmissionCard."],
        anatomy=["person: Avatar + título + descripción + acción", "definition: etiqueta + valor + acción opcional", "navigation: título + chevron"],
        props=[P("type", "'person' | 'definition' | 'navigation'", "'definition'", False, "Formato."),
               P("title", "string", "—", True, "Título o etiqueta."),
               P("description", "string", "—", False, "Descripción (person) o valor (definition)."),
               P("avatarName", "string", "—", False, "Solo person."),
               P("action", "{ label: string; onPress: () => void; tone?: 'default' | 'danger' }", "—", False, "Acción a la derecha."),
               P("href", "string", "—", False, "Solo navigation: destino."),
               P("hasDivider", "boolean", "true", False, "Línea inferior.")],
        variants={"type": ["person", "definition", "navigation"]}, states=["default", "hover (navigation)"],
        tokens=["size.space.large", "size.space.medium", "divider.color", "typography.overline", "typography.body-small", "typography.heading-small"],
        interaction=["navigation: toda la fila es clicable."],
        a11y=["Listas con `<ul>`; definition dentro de `<dl>` con `<dt>`/`<dd>`."],
        composition=["DataList, listas de surfers."],
        antipatterns=["Mezclar tipos dentro de la misma lista."],
        deps=["Avatar", "Heading", "Text", "Button", "Icon", "Divider"],
        example='<ListItem type="definition" title="PLAN RENEWS" description="26 sept 2026" action={{ label: "Cancel your plan", tone: "danger", onPress: openCancel }} />',
        examples_bad='<div className="row">…</div>',
    ),
    dict(
        name="TagChip", category="molecule", status="beta", figma="13:139",
        purpose="Chip seleccionable o eliminable.",
        when=["Filtros (nivel, tipo de ola), etiquetas que el usuario añade o quita."],
        when_not=["Información estática: Tag o Badge."],
        anatomy=["Contenedor píldora", "Label", "Botón quitar opcional"],
        props=[P("label", "string", "—", True, "Texto."),
               P("isSelected", "boolean", "false", False, "Seleccionado."),
               P("onToggle", "() => void", "—", False, "Selección."),
               P("onRemove", "() => void", "—", False, "Muestra botón quitar.")],
        variants={}, states=["default", "hover", "selected"],
        tokens=["tag.radius", "tag.padding-horizontal", "color.action.secondary.*", "color.background.brand-subtle", "color.border.brand", "color.text.brand"],
        interaction=["Clic alterna; el botón quitar no alterna."],
        a11y=["`<button aria-pressed>`; quitar es otro botón con `aria-label=\"Remove {label}\"`."],
        composition=["Grupos horizontales con wrap y gap `size.space.small`."],
        antipatterns=["Usar TagChip para estados del sistema."],
        deps=["Text", "Icon"],
        example='<TagChip label="Advanced" isSelected onToggle={toggle} onRemove={remove} />',
        examples_bad='<Badge onClick={toggle}>Advanced</Badge>',
    ),
    dict(
        name="Stat", category="molecule", status="stable", figma="13:154",
        purpose="Muestra una métrica con su etiqueta y una tendencia opcional.",
        when=["Resumen de la cola (Pending, Reviewed) y del plan (Cycle submissions, Renews)."],
        when_not=["Series temporales: gráfico (planificado)."],
        anatomy=["Etiqueta", "Valor (`typography.metric`)", "Tendencia opcional (icono + texto)"],
        props=[P("label", "string", "—", True, "Qué se mide."),
               P("value", "string | number", "—", True, "Valor formateado."),
               P("trend", "{ direction: 'up' | 'down'; label: string }", "—", False, "Variación.")],
        variants={"trend": ["none", "up"]}, states=["—"],
        tokens=["stat.background", "stat.label", "stat.value", "card.radius", "size.space.xl", "typography.metric", "color.feedback.success.foreground"],
        interaction=["No interactivo."],
        a11y=["Etiqueta y valor en el mismo `<div role=group>` con `aria-label`.", "La tendencia se lee como texto."],
        composition=["Rejilla de 2 columnas con gap `size.space.xl`."],
        antipatterns=["Tendencia solo con color."],
        deps=["Text", "Icon"],
        example='<Stat label="Pending" value={3} />',
        examples_bad='<div className="stat"><b>3</b></div>',
    ),
    dict(
        name="Notification", category="molecule", status="stable", figma="13:209",
        purpose="Comunica un mensaje del sistema con tono, acción y cierre.",
        when=["Éxito de un envío, plazo cercano, error de subida, info de proceso."],
        when_not=["Errores de un campo: FormField.", "Decisiones bloqueantes: Modal."],
        anatomy=["Icono en contenedor tintado", "Título", "Descripción", "Acción opcional", "Cerrar opcional"],
        props=[P("tone", "'info' | 'success' | 'warning' | 'danger'", "'info'", False, "Tono."),
               P("title", "string", "—", True, "Mensaje principal."),
               P("description", "string", "—", False, "Detalle."),
               P("action", "{ label: string; onPress: () => void }", "—", False, "Acción."),
               P("onDismiss", "() => void", "—", False, "Muestra botón cerrar.")],
        variants={"tone": ["info", "success", "warning", "danger"]}, states=["visible", "dismissed"],
        tokens=["notification.background", "notification.border", "notification.radius", "color.feedback.*", "typography.heading-small", "typography.body-small"],
        interaction=["info/success se pueden autocerrar a los 6s; warning/danger no."],
        a11y=["info/success `role=status`; warning/danger `role=alert`.", "El cierre es un botón con `aria-label=\"Dismiss\"`."],
        composition=["Pila en la esquina superior derecha (`z-index.toast`) o en línea sobre el contenido."],
        antipatterns=["Más de 3 notificaciones visibles.", "Mensajes de error que desaparecen solos."],
        deps=["Icon", "Heading", "Text", "Button"],
        example='<Notification tone="success" title="Submission sent" description="Your coach has 48h to review your clip." />',
        examples_bad='alert("Upload failed")',
    ),
    dict(
        name="Breadcrumb", category="molecule", status="beta", figma="13:210",
        purpose="Muestra la posición del usuario dentro de una jerarquía.",
        when=["Vistas de detalle de 3+ niveles (Surfers › Surfer › Clip)."],
        when_not=["Vistas de primer nivel del Sidebar."],
        anatomy=["Enlaces", "Separadores chevron", "Elemento actual"],
        props=[P("items", "Array<{ label: string; href?: string }>", "—", True, "El último es la página actual.")],
        variants={}, states=["—"],
        tokens=["color.text.brand", "color.text.primary", "color.icon.secondary", "typography.body-small", "size.space.small"],
        interaction=["Enlaces navegan; el actual no es enlace."],
        a11y=["`<nav aria-label=\"Breadcrumb\">` + `<ol>`; actual con `aria-current=page`."],
        composition=["Encima de PageHeader en vistas de detalle."],
        antipatterns=["Breadcrumb como sustituto del Sidebar."],
        deps=["Text", "Icon"],
        example='<Breadcrumb items={[{ label: "Surfers", href: "/surfers" }, { label: "Alejandro García" }]} />',
        examples_bad='<p>Surfers / Alejandro</p>',
    ),
    dict(
        name="Pagination", category="molecule", status="beta", figma="13:221",
        purpose="Navega entre páginas de una lista larga.",
        when=["History con más de 20 revisiones."],
        when_not=["Listas cortas o feeds continuos."],
        anatomy=["Anterior", "Páginas", "Elipsis", "Siguiente"],
        props=[P("page", "number", "—", True, "Página actual (1-based)."),
               P("pageCount", "number", "—", True, "Total."),
               P("onPageChange", "(page: number) => void", "—", True, "Cambio.")],
        variants={}, states=["first", "middle", "last"],
        tokens=["button.*", "size.space.xs"],
        interaction=["Anterior se deshabilita en la primera página y Siguiente en la última."],
        a11y=["`<nav aria-label=\"Pagination\">`; página actual con `aria-current=page`."],
        composition=["Debajo de la lista que pagina."],
        antipatterns=["Paginación con 1 página."],
        deps=["Button", "Text"],
        example='<Pagination page={2} pageCount={8} onPageChange={setPage} />',
        examples_bad='<a>Next</a>',
    ),
    dict(
        name="NavigationItem", category="molecule", status="stable", figma="13:293",
        purpose="Entrada de navegación principal con icono y etiqueta.",
        when=["Dentro de Sidebar."],
        when_not=["Acciones: Button."],
        anatomy=["Icono 28px", "Etiqueta", "Divisor inferior"],
        props=[P("label", "string", "—", True, "Destino."),
               P("icon", "IconName", "—", True, "Icono."),
               P("href", "string", "—", True, "URL."),
               P("isActive", "boolean", "false", False, "Página actual.")],
        variants={}, states=["default", "hover", "active"],
        tokens=["navigation-item.*", "color.action.ghost.background-hover", "size.space.large"],
        interaction=["Hover tinta el fondo."],
        a11y=["`<a>` con `aria-current=page` si está activo.", "Activo se distingue por color y por icono relleno de marca, no solo por color de texto."],
        composition=["Solo dentro de Sidebar."],
        antipatterns=["Más de un activo a la vez."],
        deps=["Icon", "Text"],
        example='<NavigationItem label="Queue" icon="play-circle" href="/queue" isActive />',
        examples_bad='<div onClick={go}>Queue</div>',
    ),
    # -------------------------------------------------------------- ORGANISMS
    dict(
        name="Sidebar", category="organism", status="stable", figma="14:84",
        purpose="Navegación principal fija en escritorio.",
        when=["Todas las vistas autenticadas de Coach y Surfer en ≥ 1024px."],
        when_not=["Móvil: NavigationBar inferior (planificado)."],
        anatomy=["Lista de NavigationItem", "Logo al pie"],
        props=[P("product", "'coach' | 'surfer'", "—", True, "Define los items por defecto."),
               P("activeHref", "string", "—", True, "Item activo."),
               P("items", "Array<NavigationItemProps>", "según product", False, "Sobrescribe los items (máx. 5).")],
        variants={"product": ["coach", "surfer"]}, states=["—"],
        tokens=["sidebar.background", "sidebar.width", "navigation-item.*"],
        interaction=["Fijo al hacer scroll (`z-index.sticky`)."],
        a11y=["`<nav aria-label=\"Main\">`; un solo `aria-current`."],
        composition=["Slot de items (máx. 5) + Logo.", "No personalizable: ancho, fondo, posición del logo."],
        antipatterns=["Añadir acciones (botones) al Sidebar."],
        deps=["NavigationItem"],
        example='<Sidebar product="coach" activeHref="/queue" />',
        examples_bad='<Sidebar style={{ width: 200 }} />',
    ),
    dict(
        name="PageHeader", category="organism", status="stable", figma="14:116",
        purpose="Cabecera de cada vista con título, subtítulo y acciones.",
        when=["Primera sección de toda vista dentro de DashboardTemplate."],
        when_not=["Títulos de sección internos: Heading medium."],
        anatomy=["Título (Heading display, h1)", "Subtítulo opcional", "Slot Actions (máx. 2)"],
        props=[P("title", "string", "—", True, "Saludo o título."),
               P("subtitle", "string", "—", False, "Texto de apoyo."),
               P("actions", "ReactNode", "—", False, "Tag, Avatar o Button (máx. 2).")],
        variants={"context": ["coach", "surfer"]}, states=["—"],
        tokens=["typography.display", "color.text.brand", "size.space.small", "size.space.medium", "size.layout.content-width"],
        interaction=["No interactivo; las acciones lo son."],
        a11y=["Único h1 de la vista."],
        composition=["Slot Header de DashboardTemplate."],
        antipatterns=["Más de dos acciones; usar un menú."],
        deps=["Heading", "Text", "Tag", "Avatar"],
        example='<PageHeader title="Welcome, Alejandro" subtitle="Connect with your surfers" actions={<Avatar name="Coach" tone="elite" />} />',
        examples_bad='<h1 style={{ fontSize: 40 }}>Welcome</h1>',
    ),
    dict(
        name="SubmissionCard", category="organism", status="stable", figma="14:223",
        purpose="Resume un clip enviado para revisión y su acción principal.",
        when=["Cola del coach, lista de envíos del surfer."],
        when_not=["Revisión ya entregada en History: ReviewCard (planificado)."],
        anatomy=["Cabecera: Avatar + nombre + Badge de plan + Badge de estado", "Título del clip + fecha + metadatos", "Nota del surfer (opcional)", "Pie: Tag de plazo + Button primary"],
        props=[P("surfer", "{ name: string; plan: 'pay-as-you-go' | 'elite' | 'progression' }", "—", True, "Quién envía."),
               P("status", "'pending' | 'in-review' | 'review-ready' | 'overdue'", "—", True, "Estado."),
               P("clipTitle", "string", "—", True, "Maniobra."),
               P("submittedAt", "string", "—", True, "Fecha formateada."),
               P("meta", "string", "—", False, "Stance · nivel · spot."),
               P("note", "string", "—", False, "Mensaje del surfer."),
               P("deadline", "{ label: string; tone: 'on-track' | 'due-soon' | 'overdue' }", "—", True, "Plazo."),
               P("action", "{ label: string; icon?: IconName; onPress: () => void }", "—", True, "Acción principal.")],
        variants={"deadline": ["on-track", "due-soon", "overdue"]}, states=["—"],
        tokens=["card.background", "card.border", "card.radius", "card.padding", "card.gap", "color.background.surface-sunken", "size.layout.content-width"],
        interaction=["Solo el botón es interactivo; la tarjeta no es clicable entera."],
        a11y=["`<article>` con el título como h3 y `aria-labelledby`."],
        composition=["En lista: columna con gap `size.space.large`.", "Personalizable: textos, tonos y acción. No personalizable: orden de bloques."],
        antipatterns=["Dos botones primary en la tarjeta.", "Ocultar el estado."],
        deps=["Avatar", "Heading", "Text", "Badge", "Tag", "Button"],
        example='<SubmissionCard surfer={{ name: "Khata Kraiwan", plan: "elite" }} status="in-review" clipTitle="Frontside snap" submittedAt="31 ago 2026, 18:01" deadline={{ label: "1h 9m left", tone: "due-soon" }} action={{ label: "View & Download", icon: "eye", onPress }} />',
        examples_bad='<Card><b>Frontside snap</b><button className="blue">View</button></Card>',
    ),
    dict(
        name="DataList", category="organism", status="stable", figma="14:224",
        purpose="Sección de datos de solo lectura con título y filas de definición.",
        when=["Account & Billing, Surf Profile, Legal."],
        when_not=["Datos tabulares comparables: DataTable (planificado)."],
        anatomy=["Título con icono (Heading medium)", "Tarjeta con ListItem type=definition o navigation"],
        props=[P("title", "string", "—", True, "Título de sección."),
               P("icon", "IconName", "—", False, "Icono del título."),
               P("items", "Array<ListItemProps>", "—", True, "Filas.")],
        variants={}, states=["—"],
        tokens=["card.background", "card.border", "card.radius", "color.background.brand-subtle", "size.space.medium"],
        interaction=["Las acciones de fila son las únicas interactivas."],
        a11y=["`<section aria-labelledby>` con `<h2>` y `<dl>`."],
        composition=["Apilar secciones con gap `size.space.xl`."],
        antipatterns=["Mezclar campos editables: usar FormSection."],
        deps=["ListItem", "Heading", "Icon"],
        example='<DataList title="Account & Billing" icon="user" items={rows} />',
        examples_bad='<table>…</table>',
    ),
    dict(
        name="EmptyState", category="organism", status="stable", figma="14:277",
        purpose="Explica por qué una zona está vacía y ofrece la siguiente acción.",
        when=["Cola vacía, historial vacío, sin surfers."],
        when_not=["Errores: Notification danger."],
        anatomy=["Icono decorativo", "Mensaje", "Acción opcional (Button)"],
        props=[P("message", "string", "—", True, "Estado actual en lenguaje del usuario."),
               P("icon", "IconName", "'info'", False, "Icono."),
               P("action", "{ label: string; icon?: IconName; onPress: () => void }", "—", False, "Siguiente paso.")],
        variants={"action": ["false", "true"]}, states=["—"],
        tokens=["card.background", "card.radius", "color.background.canvas", "color.text.tertiary", "size.space.xl"],
        interaction=["Solo la acción es interactiva."],
        a11y=["Icono `aria-hidden`; el mensaje es texto real."],
        composition=["Ocupa el lugar de la lista vacía."],
        antipatterns=["Mensajes que culpan al usuario."],
        deps=["Icon", "Text", "Button"],
        example='<EmptyState message="No submissions waiting for review." />',
        examples_bad='<p>Nothing here</p>',
    ),
    dict(
        name="Modal", category="organism", status="stable", figma="14:348",
        purpose="Diálogo para una decisión o tarea corta que interrumpe el flujo.",
        when=["Cancelar plan, pedir cambio de coach, confirmar acciones destructivas."],
        when_not=["Información no bloqueante: Notification.", "Formularios largos: página propia."],
        anatomy=["Título + botón cerrar", "Descripción", "Slot Content", "Pie: acción secundaria + principal"],
        props=[P("isOpen", "boolean", "—", True, "Visibilidad."),
               P("title", "string", "—", True, "Título."),
               P("description", "string", "—", False, "Contexto."),
               P("tone", "'default' | 'danger'", "'default'", False, "danger usa Button danger."),
               P("primaryAction", "{ label: string; onPress: () => void }", "—", True, "Acción principal."),
               P("secondaryAction", "{ label: string; onPress: () => void }", "—", False, "Cancelar."),
               P("onClose", "() => void", "—", True, "Cierre (X, Escape, overlay)."),
               P("children", "ReactNode", "—", False, "Slot Content.")],
        variants={"tone": ["default", "danger"]}, states=["open", "closed"],
        tokens=["modal.background", "modal.overlay", "modal.radius", "modal.padding", "modal.shadow", "z-index.modal", "motion.transition-enter"],
        interaction=["Entra con `motion.transition-enter`; Escape y overlay cierran (salvo tone=danger, donde el overlay no cierra)."],
        a11y=["`role=dialog`, `aria-modal=true`, `aria-labelledby` al título.", "Foco atrapado; vuelve al disparador al cerrar.", "El primer foco va al primer campo o a la acción secundaria en danger."],
        composition=["Slot Content admite FormField, Text y listas cortas."],
        antipatterns=["Modales encadenados.", "Modal sin forma de cerrar."],
        deps=["Heading", "Text", "Button", "Icon", "FormField"],
        example='<Modal isOpen tone="danger" title="Cancel your plan?" primaryAction={{ label: "Cancel plan", onPress: cancel }} secondaryAction={{ label: "Keep my plan", onPress: close }} onClose={close} />',
        examples_bad='<div className="popup" style={{ zIndex: 9999 }}>…</div>',
    ),
    dict(
        name="FormSection", category="organism", status="stable", figma="14:349",
        purpose="Formulario completo con campos y acciones.",
        when=["Log in, Create account, pasos de onboarding, editar perfil."],
        when_not=["Un único campo en línea: FormField."],
        anatomy=["Tarjeta con FormFields", "Enlaces auxiliares", "Acción primary a ancho completo", "Acción secondary opcional"],
        props=[P("onSubmit", "(event: FormEvent) => void", "—", True, "Envío."),
               P("children", "ReactNode", "—", True, "FormFields."),
               P("primaryAction", "{ label: string; icon?: IconName; isLoading?: boolean }", "—", True, "Envío."),
               P("secondaryAction", "{ label: string; onPress: () => void }", "—", False, "Alternativa."),
               P("errorSummary", "string[]", "—", False, "Resumen si hay más de un error.")],
        variants={}, states=["default", "submitting", "error"],
        tokens=["card.*", "size.layout.form-width", "size.space.large", "size.space.medium"],
        interaction=["Enter envía; el botón entra en loading mientras se envía."],
        a11y=["`<form>` con `aria-describedby` al resumen de errores; el foco va al primer error."],
        composition=["Slot Form de AuthTemplate o columna de contenido."],
        antipatterns=["Dos acciones primary.", "Validar mientras se escribe."],
        deps=["FormField", "Button", "Notification"],
        example='<FormSection onSubmit={login} primaryAction={{ label: "Login", icon: "log-in" }} secondaryAction={{ label: "Create new account", onPress: goSignup }}>…</FormSection>',
        examples_bad='<form><input/><input/><button>Go</button></form>',
    ),
]
