"""Single source for component documentation. build_docs.py turns it into
*.docs.md, *.examples.md, *.tokens.json and MANIFEST.json.

Every field is required unless marked optional (since, changes). All text is in English."""

FIGMA_FILE = "https://www.figma.com/design/GZRi3cvtWVfu0MTxPvPEcY/Design-System"

P = lambda name, type_, default, required, desc: dict(name=name, type=type_, default=default, required=required, desc=desc)

SPECS = [
    # ------------------------------------------------------------------ ATOMS
    dict(
        name="Button", category="atom", status="stable", figma="8:425",
        purpose="Triggers an action in the current view.",
        when=["Submit a form, confirm or cancel a decision.", "Start a flow (Send new submission, View & Download).", "Only one primary variant per view: the main action."],
        when_not=["To navigate to another URL: use a link (`as=\"a\"`) or `ListItem` type=navigation.", "To toggle a setting: use `Switch`.", "For selectable filters: use `TagChip`."],
        anatomy=["Container (background, border, radius `button.radius`)", "Optional leading icon (`Icon`)", "Label (`typography.button` style)", "Optional trailing icon (`Icon`)"],
        props=[P("children", "ReactNode", "—", True, "Visible button text. Verb + object: 'Send request'."),
               P("variant", "'primary' | 'secondary' | 'ghost' | 'danger' | 'highlight'", "'primary'", False, "Visual hierarchy of the action. highlight is the warm secondary (Change coach, Get more submissions)."),
               P("size", "'small' | 'medium' | 'large'", "'medium'", False, "Height 32 / 44 / 52 px."),
               P("leadingIcon", "IconName", "—", False, "Icon before the text."),
               P("trailingIcon", "IconName", "—", False, "Icon after the text."),
               P("isDisabled", "boolean", "false", False, "Disables the button (aria-disabled)."),
               P("isLoading", "boolean", "false", False, "Replaces the leading icon with a Spinner and blocks clicks."),
               P("isFullWidth", "boolean", "false", False, "Fills the container width (forms)."),
               P("type", "'button' | 'submit' | 'reset'", "'button'", False, "HTML type."),
               P("onPress", "() => void", "—", False, "Action on press (click, Enter, Space).")],
        variants={"variant": ["primary", "secondary", "ghost", "danger", "highlight"], "size": ["small", "medium", "large"]},
        states=["default", "hover", "pressed", "focus", "disabled", "loading"],
        tokens=["button.primary.*", "button.secondary.*", "button.ghost.*", "button.danger.*", "button.highlight.*", "button.disabled.*", "button.primary.opacity-disabled", "button.radius", "button.gap", "button.padding-horizontal.*", "button.typography", "elevation.focus", "size.layout.control-height*"],
        interaction=["Hover and pressed change the background with `motion.transition-fast`.", "Enter and Space trigger `onPress`.", "While loading the width does not change and `aria-busy=true`."],
        a11y=["Native `<button>` element; if it navigates, an `<a>` with the same style.", "Visible focus: 2px `color.border.focus` outline outside the button.", "Icon-only buttons need an `aria-label` and a `Tooltip`.", "Primary keeps the Coach Platform CTA gradient (ocean 600→400, #3b8eaa → #5aaec8). White text on it is 3.7–2.5:1, below WCAG AA 4.5:1: a known exception chosen by product design. Secondary, ghost and danger meet 4.5:1.", "Disabled uses `aria-disabled` so screen readers can still find it. A disabled primary keeps its gradient at 50% opacity (Create account before the form is valid); the other variants use `button.disabled.*`."],
        composition=["At most one primary per view or per Modal.", "In a group, the main action goes on the right (Modal) or on top at full width (FormSection).", "Do not nest interactive elements inside."],
        antipatterns=["Two primary buttons in the same view.", "Changing colors with ad-hoc styles instead of `variant`.", "Using `ghost` for destructive actions.", "A red text-only action: use Link tone=danger.", "Generic text ('Click here', 'OK')."],
        changes=['Added the highlight variant.', 'A disabled primary now keeps its faded brand gradient.'],
        deps=["Icon", "Spinner"],
        example='<Button variant="primary" leadingIcon="eye" onPress={openReview}>View & Download</Button>',
        examples_bad='<Button style={{ background: "#3b8eaa" }}>OK</Button>',
    ),
    dict(
        name="Icon", category="atom", status="stable", figma="7:6",
        purpose="Shows a line pictogram from the Alora icon set.",
        when=["Reinforce the meaning of a text (buttons, tags, navigation).", "Icon-only buttons when space is tight and the meaning is universal (close, search)."],
        when_not=["As the only way to communicate a state: add text.", "For illustrations or logos: use images or the Sidebar logo."],
        anatomy=["24×24 box", "2px stroke with round caps (Lucide style)"],
        props=[P("name", "IconName", "—", True, "home, list, user, users, calendar, play-circle, bell, eye, clock, check, close, chevron-right, chevron-left, search, info, plus, upload, log-in, log-out, edit, repeat, warning, check-circle, star, trending-up, mail, lock, trash, video, trending-down, download, play, pause, volume, maximize, shield, alert-circle, file-text, plus-circle, x-circle."),
               P("size", "'xs' | 'sm' | 'md' | 'lg' | 'xl'", "'lg'", False, "12 / 16 / 20 / 24 / 32 px (`size.icon.*`)."),
               P("tone", "'primary' | 'secondary' | 'brand' | 'inherit'", "'inherit'", False, "Color `color.icon.*`; inherit uses currentColor."),
               P("label", "string", "—", False, "When set, the icon is meaningful (`role=img` + `aria-label`). Otherwise `aria-hidden`.")],
        variants={"size": ["xs", "sm", "md", "lg", "xl"], "tone": ["primary", "secondary", "brand", "inherit"]},
        states=["—"],
        tokens=["color.icon.primary", "color.icon.secondary", "color.icon.brand", "size.icon.*"],
        interaction=["Not interactive on its own."],
        a11y=["Decorative by default (`aria-hidden=true`).", "With `label` it becomes `role=img`.", "Contrast ≥ 3:1 against the background when it carries information."],
        composition=["Inside Button, Tag, NavigationItem, Notification, Input.", "The parent component decides the color (`tone=inherit`)."],
        antipatterns=["Icons from other libraries mixed with the set.", "Changing the stroke width.", "An icon with no text or aria-label on a control."],
        changes=['Added download, play, pause, volume, maximize, shield, alert-circle, file-text, plus-circle and x-circle.'],
        deps=[],
        example='<Icon name="clock" size="sm" tone="inherit" />',
        examples_bad='<img src="clock.png" />',
    ),
    dict(
        name="Label", category="atom", status="stable", figma="9:11",
        purpose="Names a form control.",
        when=["Above Input or Textarea, or to the right of Checkbox, Radio and Switch."],
        when_not=["As a section title: use Heading.", "As helper text: use Text inside FormField."],
        anatomy=["Text (`typography.label`)", "Optional required mark (*)"],
        props=[P("children", "ReactNode", "—", True, "Field name."),
               P("htmlFor", "string", "—", True, "id of the associated control."),
               P("isRequired", "boolean", "false", False, "Adds * and requires aria-required on the control."),
               P("isDisabled", "boolean", "false", False, "Dims the label (`color.text.disabled`).")],
        variants={}, states=["default", "disabled"],
        tokens=["typography.label", "color.text.primary", "color.text.disabled", "color.feedback.danger.foreground"],
        interaction=["Clicking the label focuses or toggles the control."],
        a11y=["Native `<label for>`.", "The asterisk is decorative (`aria-hidden`); required state is conveyed with `aria-required`."],
        composition=["Only inside FormField or next to Checkbox / Radio / Switch."],
        antipatterns=["Using the placeholder as the label.", "Typing labels in uppercase: the style already defines the typography."],
        deps=[],
        example='<Label htmlFor="email" isRequired>Email</Label>',
        examples_bad='<span style={{ fontWeight: 600 }}>Email</span>',
    ),
    dict(
        name="Text", category="atom", status="stable", figma="9:65",
        purpose="Shows reading text and metadata with a type role and a semantic tone.",
        when=["Paragraphs, descriptions, metadata, dates and overlines."],
        when_not=["Titles: use Heading.", "Form labels: use Label."],
        anatomy=["Text"],
        props=[P("children", "ReactNode", "—", True, "Content."),
               P("role", "'body-large' | 'body-medium' | 'body-small' | 'caption' | 'overline'", "'body-medium'", False, "Type style (`typography.*`)."),
               P("tone", "'primary' | 'secondary' | 'tertiary' | 'brand' | 'danger'", "'primary'", False, "Semantic color."),
               P("as", "'p' | 'span' | 'div' | 'dd' | 'dt'", "'p'", False, "HTML element.")],
        variants={"role": ["body-large", "body-medium", "body-small", "caption", "overline"], "tone": ["primary", "secondary", "tertiary", "brand", "danger"]},
        states=["—"],
        tokens=["typography.body-*", "typography.caption", "typography.overline", "color.text.*", "color.feedback.danger.foreground"],
        interaction=["Not interactive."],
        a11y=["`tertiary` meets 4.5:1 on surface-raised, but is not used for critical information.", "Acronyms in `overline` are typed in uppercase in the content; do not rely on text-transform for them."],
        composition=["Free to use inside molecules and organisms."],
        antipatterns=["Combining size and weight by hand instead of `role`.", "Using `brand` widely for text that is not a link."],
        deps=[],
        example='<Text role="body-small" tone="tertiary">Submitted 31 ago 2026, 18:01</Text>',
        examples_bad='<p style={{ fontSize: 12, color: "#4d6e87" }}>Submitted…</p>',
    ),
    dict(
        name="Heading", category="atom", status="stable", figma="9:77",
        purpose="Titles a view, section or card while respecting the document hierarchy.",
        when=["View greeting (display, h1).", "Section titles (medium, h2) and card titles (small, h3)."],
        when_not=["To emphasize text within a paragraph: use Text."],
        anatomy=["Text (`typography.display` or `typography.heading-*`)"],
        props=[P("children", "ReactNode", "—", True, "Title text."),
               P("level", "'display' | 'large' | 'medium' | 'small'", "'medium'", False, "Visual style."),
               P("as", "'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6'", "from level", False, "Semantic level; do not skip levels.")],
        variants={"level": ["display", "large", "medium", "small"]}, states=["—"],
        tokens=["typography.display", "typography.heading-large", "typography.heading-medium", "typography.heading-small", "color.text.primary"],
        interaction=["Not interactive."],
        a11y=["Only one h1 per view.", "Level order reflects structure, not size."],
        composition=["PageHeader uses display; DataList uses medium; SubmissionCard uses small."],
        antipatterns=["Using Heading for bold text that is not a title.", "Jumping from h1 to h4."],
        deps=[],
        example='<Heading level="display" as="h1">Welcome, Alejandro</Heading>',
        examples_bad='<div className="big-bold">Welcome</div>',
    ),
    dict(
        name="Input", category="atom", status="stable", figma="9:161",
        purpose="Collects one line of text.",
        when=["Email, password, name, search (through SearchField)."],
        when_not=["Long text: use Textarea.", "Fixed options: use Radio or a Select (planned)."],
        anatomy=["Container (background `input.background`, border `input.border.*`, radius `input.radius`)", "Optional leading icon", "Value or placeholder", "Optional trailing icon (show password)"],
        props=[P("id", "string", "—", True, "Links the Label and messages."),
               P("value", "string", "—", False, "Controlled value."),
               P("placeholder", "string", "—", False, "Format example; never replaces the Label."),
               P("type", "'text' | 'email' | 'password' | 'search' | 'tel'", "'text'", False, "HTML type."),
               P("leadingIcon", "IconName", "—", False, "Icon before the value."),
               P("trailingIcon", "IconName", "—", False, "Icon or action after the value."),
               P("hasError", "boolean", "false", False, "Error border and `aria-invalid`."),
               P("isDisabled", "boolean", "false", False, "Disabled."),
               P("onChange", "(value: string) => void", "—", False, "Value change.")],
        variants={}, states=["default", "hover", "focus", "error", "disabled", "filled"],
        tokens=["input.background", "input.foreground", "input.placeholder", "input.border.default", "input.border.hover", "input.border.focus", "input.border.error", "input.radius", "input.padding-horizontal", "input.typography", "size.layout.control-height", "size.border.focus"],
        interaction=["Focus: 2px `input.border.focus` border.", "Error: 2px `input.border.error` border; FormField renders the message."],
        a11y=["Always with an associated Label (FormField guarantees it).", "`aria-invalid` and `aria-describedby` pointing to helper and error text.", "Correct `autocomplete` (email, current-password)."],
        composition=["Use inside FormField. Outside a form, only through SearchField."],
        antipatterns=["Placeholder as the only label.", "Red borders with no error message."],
        deps=["Icon"],
        example='<Input id="email" type="email" value={email} onChange={setEmail} />',
        examples_bad='<input style={{ border: "1px solid red" }} placeholder="Email" />',
    ),
    dict(
        name="Textarea", category="atom", status="stable", figma="9:177",
        purpose="Collects multiple lines of text.",
        when=["Surfer note to the coach, reason for changing coach."],
        when_not=["Single-line values: use Input."],
        anatomy=["Container (`input.*` tokens)", "Value or placeholder", "Optional counter"],
        props=[P("id", "string", "—", True, "Links the Label."),
               P("value", "string", "—", False, "Controlled value."),
               P("maxLength", "number", "—", False, "Shows an 'n / max' counter."),
               P("rows", "number", "4", False, "Initial height."),
               P("hasError", "boolean", "false", False, "Error state."),
               P("isDisabled", "boolean", "false", False, "Disabled."),
               P("onChange", "(value: string) => void", "—", False, "Value change.")],
        variants={}, states=["default", "focus", "error", "disabled"],
        tokens=["input.*", "typography.body-medium", "typography.caption", "color.text.tertiary"],
        interaction=["Grows with the content up to 8 rows, then scrolls."],
        a11y=["Counter linked with `aria-describedby` and announced when the limit is reached."],
        composition=["Inside FormField or the Modal Content slot."],
        antipatterns=["Using it for a single short value."],
        deps=[],
        example='<Textarea id="note" maxLength={280} value={note} onChange={setNote} />',
        examples_bad='<textarea style={{ height: 112 }} />',
    ),
    dict(
        name="Checkbox", category="atom", status="stable", figma="12:44",
        purpose="Lets the user check one or more independent options.",
        when=["Accept terms, 'Remember me', select several items."],
        when_not=["One option among several: Radio.", "Setting with immediate effect: Switch."],
        anatomy=["18×18 box (`checkbox.radius`)", "Check mark or dash (indeterminate)", "Label"],
        props=[P("label", "ReactNode", "—", True, "Visible text."),
               P("isChecked", "boolean | 'indeterminate'", "false", False, "State."),
               P("isDisabled", "boolean", "false", False, "Disabled."),
               P("onChange", "(checked: boolean) => void", "—", False, "Change.")],
        variants={"checked": ["false", "true", "indeterminate"]}, states=["default", "focus", "disabled"],
        tokens=["checkbox.border", "checkbox.background-checked", "checkbox.foreground-checked", "checkbox.radius", "color.border.focus"],
        interaction=["Clicking the box or label toggles it.", "Space toggles it when focused."],
        a11y=["Native `<input type=checkbox>`.", "Indeterminate uses `aria-checked=mixed`.", "Clickable area ≥ 24×24 including the label."],
        composition=["Groups go inside a `<fieldset>` with a `<legend>`."],
        antipatterns=["A checkbox that triggers an immediate action.", "No visible label."],
        deps=["Icon", "Label"],
        example='<Checkbox label="Remember me" isChecked={remember} onChange={setRemember} />',
        examples_bad='<div onClick={toggle} className="box" />',
    ),
    dict(
        name="Radio", category="atom", status="stable", figma="12:71",
        purpose="Lets the user pick one option within a group.",
        when=["2–5 visible mutually exclusive options (Regular/Goofy stance, level)."],
        when_not=["More than 5 options: Select (planned).", "Multiple choices: Checkbox."],
        anatomy=["18×18 circle", "Inner dot when selected", "Label"],
        props=[P("label", "ReactNode", "—", True, "Visible text."),
               P("value", "string", "—", True, "Option value."),
               P("name", "string", "—", True, "Group name."),
               P("isSelected", "boolean", "false", False, "Selected."),
               P("isDisabled", "boolean", "false", False, "Disabled.")],
        variants={"selected": ["false", "true"]}, states=["default", "focus", "disabled"],
        tokens=["radio.border", "radio.border-checked", "radio.dot", "color.border.focus"],
        interaction=["Arrow keys move the selection within the group."],
        a11y=["`<input type=radio>` inside a `<fieldset>` with a `<legend>`, or a named `role=radiogroup`."],
        composition=["Always in a group of at least 2."],
        antipatterns=["A lone radio button.", "A group with no default option when the value is required."],
        deps=["Label"],
        example='<Radio name="stance" value="goofy" label="Goofy" isSelected={stance === "goofy"} />',
        examples_bad='<Radio label="Accept terms" />',
    ),
    dict(
        name="Switch", category="atom", status="stable", figma="12:91",
        purpose="Turns a setting on or off with immediate effect.",
        when=["Preferences saved instantly (notifications)."],
        when_not=["When the change needs a Save button: Checkbox."],
        anatomy=["36×20 track (`switch.radius`)", "16×16 thumb", "Label"],
        props=[P("label", "ReactNode", "—", True, "Visible text."),
               P("isOn", "boolean", "false", False, "State."),
               P("isDisabled", "boolean", "false", False, "Disabled."),
               P("onChange", "(on: boolean) => void", "—", False, "Change.")],
        variants={"on": ["false", "true"]}, states=["default", "disabled"],
        tokens=["switch.track-off", "switch.track-on", "switch.thumb", "switch.radius", "color.border.default"],
        interaction=["The thumb slides with `motion.transition-base`."],
        a11y=["`role=switch` + `aria-checked`.", "State does not rely on color alone: the thumb position changes."],
        composition=["Settings lists, one per row."],
        antipatterns=["A Switch inside a form with a Save button."],
        deps=["Label"],
        example='<Switch label="Email notifications" isOn={notify} onChange={setNotify} />',
        examples_bad='<Switch label="Accept terms" />',
    ),
    dict(
        name="Avatar", category="atom", status="stable", figma="12:119",
        purpose="Represents a person with their initials.",
        when=["Next to a surfer or coach name (lists, cards, header)."],
        when_not=["As the only identifier of a person: always show the name."],
        anatomy=["Circle (`avatar.radius`)", "Initials"],
        props=[P("name", "string", "—", True, "Full name; initials are derived from it."),
               P("size", "'small' | 'medium' | 'large' | 'xlarge'", "'medium'", False, "24 / 32 / 64 / 80 px. large and xlarge show two initials; xlarge adds a brand halo (profile)."),
               P("tone", "'brand' | 'elite' | 'progression' | 'session' | 'performance' | 'neutral'", "'brand'", False, "Background color; plan tones go with a plan Badge.")],
        variants={"size": ["small", "medium", "large", "xlarge"], "tone": ["brand", "elite", "progression", "session", "performance", "neutral"]}, states=["—"],
        tokens=["avatar.background", "avatar.foreground", "avatar.radius", "color.plan.*.foreground", "color.text.inverse", "size.layout.avatar-xlarge", "elevation.halo-brand"],
        interaction=["Not interactive; if it opens the profile, wrap it in a link with the name."],
        a11y=["Initials are `aria-hidden`; the visible name next to it gives context."],
        composition=["ListItem type=person, SubmissionCard, PageHeader."],
        antipatterns=["Communicating the plan only through the avatar color."],
        changes=['Added the xlarge size and the session and performance tones.'],
        deps=[],
        example='<Avatar name="Khata Kraiwan" tone="elite" />',
        examples_bad='<div className="circle" style={{ background: "#d97706" }}>K</div>',
    ),
    dict(
        name="Badge", category="atom", status="stable", figma="12:139",
        purpose="Non-interactive label that shows a status or a plan.",
        when=["Submission status (Pending, In review, Review ready, Overdue).", "Surfer plan (Pay as you go, Elite, Progression, Session, Performance).", "On a thumbnail, a solid status (appearance=solid)."],
        when_not=["Information with an icon or a time: Tag.", "Selectable or removable items: TagChip."],
        anatomy=["Container (`badge.radius`, padding `badge.padding-*`)", "Optional icon", "Uppercase text (`typography.overline`)"],
        props=[P("children", "string", "—", True, "Status text."),
               P("tone", "'pending' | 'in-review' | 'review-ready' | 'overdue' | 'neutral' | 'plan-pay-as-you-go' | 'plan-elite' | 'plan-progression' | 'plan-session' | 'plan-performance'", "'neutral'", False, "Semantic tone."),
               P("appearance", "'subtle' | 'solid'", "'subtle'", False, "solid fills the badge (status tones only), for use on images."),
               P("icon", "IconName", "—", False, "Leading icon (check on Reviewed).")],
        variants={"tone": ["pending", "in-review", "review-ready", "overdue", "neutral", "plan-pay-as-you-go", "plan-elite", "plan-progression", "plan-session", "plan-performance"], "appearance": ["subtle", "solid"]}, states=["—"],
        tokens=["badge.radius", "badge.padding-horizontal", "badge.padding-vertical", "badge.typography", "color.status.*", "color.status.*.solid", "color.text.on-action", "color.plan.*", "color.feedback.neutral.*"],
        interaction=["Not interactive."],
        a11y=["The text names the state; color only reinforces it.", "Contrast ≥ 4.5:1 in every tone."],
        composition=["SubmissionCard (status and plan), ListItem (plan), ClipItem thumbnails (solid), ReviewCard."],
        antipatterns=["A clickable Badge.", "Inventing tones outside the list."],
        changes=['Added the plan-session and plan-performance tones, the solid appearance and the optional icon.'],
        deps=["Icon"],
        example='<Badge tone="in-review">In review</Badge>',
        examples_bad='<span style={{ color: "#f5c53a" }}>Pending</span>',
    ),
    dict(
        name="Tag", category="atom", status="stable", figma="12:167",
        purpose="Informational pill with an optional icon.",
        when=["Time left on a review, highlighted plan, context (Surf park)."],
        when_not=["Short states without an icon: Badge.", "Selectable or removable items: TagChip."],
        anatomy=["Pill container (`tag.radius`)", "Optional icon", "Text (`typography.body-small`)"],
        props=[P("children", "ReactNode", "—", True, "Text."),
               P("tone", "'brand' | 'highlight' | 'warning' | 'danger' | 'neutral'", "'brand'", False, "Semantic tone."),
               P("icon", "IconName", "—", False, "Leading icon.")],
        variants={"tone": ["brand", "highlight", "warning", "danger", "neutral"]}, states=["—"],
        tokens=["tag.background", "tag.foreground", "tag.border", "tag.radius", "tag.padding-horizontal", "color.background.highlight-subtle", "color.text.highlight", "color.feedback.*"],
        interaction=["Not interactive."],
        a11y=["If the Tag conveys urgency (warning/danger), the text says so ('1h 9m left', 'Overdue')."],
        composition=["SubmissionCard (deadline), PageHeader (plan, notifications)."],
        antipatterns=["Using Tag as a button."],
        deps=["Icon"],
        example='<Tag tone="warning" icon="clock">1h 9m left</Tag>',
        examples_bad='<Tag onClick={…}>Filter</Tag>',
    ),
    dict(
        name="Spinner", category="atom", status="stable", figma="12:180",
        purpose="Indicates a wait of unknown duration.",
        when=["Video upload, review submission, loading the queue."],
        when_not=["Measurable progress: ProgressBar.", "Loading a whole view: skeletons (planned)."],
        anatomy=["Circular track (`spinner.track`)", "Animated arc (`spinner.indicator`)"],
        props=[P("size", "'small' | 'medium' | 'large' | 'xlarge'", "'medium'", False, "16 / 24 / 32 / 80 px. xlarge is the full-screen wait (Sending your submission)."),
               P("label", "string", "'Loading'", False, "Text for screen readers.")],
        variants={"size": ["small", "medium", "large", "xlarge"]}, states=["—"],
        tokens=["spinner.track", "spinner.indicator", "size.border.focus", "size.border.heavy", "size.layout.avatar-xlarge", "motion.loop-duration"],
        interaction=["Rotates continuously; with `prefers-reduced-motion` the animation stops."],
        a11y=["`role=status` with `aria-label`.", "Respects `prefers-reduced-motion`."],
        composition=["Inside Button (isLoading) or centered in a loading EmptyState."],
        antipatterns=["Several spinners at once in one view."],
        changes=['Added the xlarge size.'],
        deps=[],
        example='<Spinner size="small" label="Uploading video" />',
        examples_bad='<img src="loader.gif" />',
    ),
    dict(
        name="Divider", category="atom", status="stable", figma="12:186",
        purpose="Separates groups of content.",
        when=["Between the stats block and the submissions list; between list rows.", "With a label, between alternatives (OR between sign-in methods)."],
        when_not=["To create space: use `size.space.*` tokens."],
        anatomy=["1px line (`divider.color`)", "Optional centered label (`typography.overline`)"],
        props=[P("orientation", "'horizontal' | 'vertical'", "'horizontal'", False, "Direction."),
               P("isDecorative", "boolean", "true", False, "When false, `role=separator`."),
               P("label", "string", "—", False, "Centered text (“OR”); the divider becomes a labelled separator.")],
        variants={"orientation": ["horizontal", "vertical"]}, states=["—"],
        tokens=["divider.color", "size.border.default", "typography.overline", "color.text.tertiary"],
        interaction=["Not interactive."],
        a11y=["Decorative by default (`aria-hidden`).", "With a label it is a `role=separator` named by the label."],
        composition=["Free to use."],
        antipatterns=["Hand-drawn borders in other colors."],
        changes=['Added the optional label.'],
        deps=[],
        example='<Divider />',
        examples_bad='<hr style={{ borderColor: "#333" }} />',
    ),
    dict(
        name="Tooltip", category="atom", status="beta", figma="12:200",
        purpose="Briefly describes a control on hover or focus.",
        when=["Icon-only buttons, abbreviations."],
        when_not=["Essential information or actions: use visible text or Notification."],
        anatomy=["Bubble (`tooltip.background`, `tooltip.radius`)", "Arrow", "Text (`typography.body-small`)"],
        props=[P("content", "string", "—", True, "Short text (≤ 60 characters)."),
               P("placement", "'top' | 'bottom'", "'top'", False, "Placement."),
               P("children", "ReactElement", "—", True, "Focusable trigger element.")],
        variants={"placement": ["top", "bottom"]}, states=["hidden", "visible"],
        tokens=["tooltip.background", "tooltip.foreground", "tooltip.radius", "tooltip.padding", "layer.tooltip"],
        interaction=["Appears after 300ms of hover, or instantly on focus; Escape closes it."],
        a11y=["`role=tooltip` linked with `aria-describedby`.", "Does not disappear while the pointer is over it (WCAG 1.4.13)."],
        composition=["Wraps an icon-only Button."],
        antipatterns=["Tooltips containing links or buttons."],
        deps=[],
        example='<Tooltip content="Close"><Button variant="ghost" leadingIcon="close" aria-label="Close" /></Tooltip>',
        examples_bad='<Tooltip content="Your plan renews on 26 sept and you will be charged…">',
    ),
    dict(
        name="Logo", category="atom", status="stable", figma="54:37", since="1.1.0",
        purpose="Shows the Alora brand mark, with or without the ALORA wordmark.",
        when=["Top of the auth screens (log in, sign up, profile selector).", "Bottom of the Sidebar."],
        when_not=["As decoration inside content.", "As a home link with no text: wrap it in a link with an accessible name."],
        anatomy=["Mark: mountains (`color.text.brand`) and sun (`color.text.highlight`)", "Optional wordmark ALORA (`typography.overline`)"],
        props=[P("size", "'small' | 'medium' | 'large'", "'medium'", False, "Mark height 24 / 36 / 56 px."),
               P("hasWordmark", "boolean", "true", False, "Shows ALORA under the mark.")],
        variants={"size": ["small", "medium", "large"], "hasWordmark": ["true", "false"]}, states=["—"],
        tokens=["color.text.brand", "color.text.highlight", "color.text.primary", "typography.overline", "size.space.2xs"],
        interaction=["Not interactive."],
        a11y=["`role=img` with `aria-label=\"Alora\"`; the SVG and the wordmark are hidden from screen readers."],
        composition=["AuthTemplate (hasLogo) and Sidebar render it; screens do not place it by hand."],
        antipatterns=["Recoloring the mark.", "Stretching it: change `size` instead."],
        deps=[],
        example='<Logo size="large" />',
        examples_bad='<img src="logo.png" width="57" />',
    ),
    dict(
        name="Link", category="atom", status="stable", figma="54:89", since="1.1.0",
        purpose="Text action that navigates or triggers a light, secondary action.",
        when=["Forgot your password?, Log in / Sign up switches, Terms and Privacy.", "Row actions in lists (Cancel your plan, Delete clip, Change coach).", "Talk to your coach next to a section title."],
        when_not=["The main action of a view or form: Button.", "An action that needs weight next to other buttons: Button secondary."],
        anatomy=["Optional leading icon", "Underlined-on-hover text", "Optional trailing icon"],
        props=[P("children", "ReactNode", "—", True, "Link text: says where it goes or what it does."),
               P("href", "string", "—", False, "Destination. Without it, Link renders a `<button>`."),
               P("onPress", "() => void", "—", False, "Action when there is no href."),
               P("tone", "'brand' | 'danger' | 'neutral'", "'brand'", False, "danger for destructive row actions (Delete clip, Cancel your plan)."),
               P("size", "'small' | 'medium'", "'medium'", False, "body-small or body-medium."),
               P("leadingIcon", "IconName", "—", False, "Icon before the text."),
               P("trailingIcon", "IconName", "—", False, "Icon after the text.")],
        variants={"tone": ["brand", "danger", "neutral"], "size": ["small", "medium"]}, states=["default", "hover", "focus"],
        tokens=["color.text.brand", "color.feedback.danger.foreground", "color.text.primary", "typography.label", "typography.body-small", "size.space.2xs"],
        interaction=["Hover underlines the text.", "Enter activates it; a button-link also responds to Space."],
        a11y=["`<a href>` when it navigates, `<button type=button>` when it acts: never a clickable `<span>`.", "Visible focus ring.", "Text alone must describe the destination; avoid 'Click here'."],
        composition=["Inline in Text, in ListItem and ClipItem actions, in SectionHeader actions, under FormSection."],
        antipatterns=["Using Link for the main call to action.", "A red Button for a row action: use Link tone=danger."],
        deps=["Icon"],
        example='<Link tone="danger" size="small" onPress={openCancel}>Cancel your plan</Link>',
        examples_bad='<span className="red" onClick={cancel}>Cancel</span>',
    ),
    dict(
        name="IconButton", category="atom", status="stable", figma="54:129", since="1.1.0",
        purpose="Square button that shows only an icon.",
        when=["Back in a TopBar, previous and next in PeriodStepper, video controls."],
        when_not=["When the action needs words to be understood: Button with a leading icon."],
        anatomy=["Square container (`button.radius`)", "Icon (`Icon`)"],
        props=[P("icon", "IconName", "—", True, "Pictogram."),
               P("label", "string", "—", True, "Accessible name (`aria-label`); also the tooltip text."),
               P("variant", "'secondary' | 'ghost'", "'secondary'", False, "secondary has a border; ghost is transparent."),
               P("size", "'small' | 'medium'", "'medium'", False, "32 / 44 px."),
               P("isDisabled", "boolean", "false", False, "aria-disabled."),
               P("onPress", "() => void", "—", False, "Action.")],
        variants={"variant": ["secondary", "ghost"], "size": ["small", "medium"]}, states=["default", "hover", "focus", "disabled"],
        tokens=["button.secondary.*", "button.ghost.*", "button.disabled.*", "button.radius", "size.layout.control-height", "size.layout.control-height-small"],
        interaction=["Same feedback as Button: hover background, Enter and Space activate."],
        a11y=["`aria-label` is required.", "Disabled uses `aria-disabled` and ignores presses.", "Target size ≥ 32px."],
        composition=["TopBar, PeriodStepper. Pair with Tooltip when the icon is not universal."],
        antipatterns=["An icon-only Button without `label`.", "Icons that need explaining."],
        deps=["Icon"],
        example='<IconButton icon="chevron-left" label="Back" onPress={goBack} />',
        examples_bad='<button><Icon name="chevron-left" /></button>',
    ),
    dict(
        name="IconTile", category="atom", status="stable", figma="54:293", since="1.1.0",
        purpose="Tinted square or circle that frames an icon or a letter.",
        when=["Leading icon of summary rows, section headers and upload areas.", "Result screens (success check, error).", "Coach initial in a review."],
        when_not=["People with a name: Avatar.", "Plain inline icons: Icon."],
        anatomy=["Container (`icon-tile.*`, square or circle)", "Icon or one letter", "Optional halo (`elevation.halo-*`)"],
        props=[P("icon", "IconName", "—", False, "Icon. Use children for a letter."),
               P("children", "ReactNode", "—", False, "Letter or short text instead of an icon."),
               P("size", "'small' | 'medium' | 'large' | 'xlarge'", "'medium'", False, "24 / 36 / 56 / 96 px."),
               P("tone", "'brand' | 'danger' | 'highlight' | 'neutral' | 'solid'", "'brand'", False, "Tint. solid is the filled teal for success."),
               P("shape", "'square' | 'circle'", "'square'", False, "Shape."),
               P("hasHalo", "boolean", "false", False, "Soft glow around the tile."),
               P("label", "string", "—", False, "Makes the tile meaningful (`role=img`).")],
        variants={"size": ["small", "medium", "large", "xlarge"], "tone": ["brand", "danger", "highlight", "neutral", "solid"], "shape": ["square", "circle"]}, states=["—"],
        tokens=["icon-tile.background", "icon-tile.foreground", "icon-tile.border", "icon-tile.radius", "size.layout.icon-tile-*", "color.feedback.danger.*", "color.action.highlight.*", "color.action.primary.background", "elevation.halo-brand", "elevation.halo-danger"],
        interaction=["Not interactive."],
        a11y=["Decorative by default; with `label` it becomes `role=img`."],
        composition=["SummaryRow, SectionHeader, Dropzone, ResultState, ReviewCard, Modal with icon."],
        antipatterns=["Using a tile as a button.", "Putting more than two characters inside."],
        deps=["Icon"],
        example='<IconTile icon="check" tone="solid" shape="circle" size="xlarge" hasHalo />',
        examples_bad='<div className="icon-bg"><Icon name="check" /></div>',
    ),
    dict(
        name="ProgressBar", category="atom", status="stable", figma="54:303", since="1.1.0",
        purpose="Shows measurable progress or how much of a limit is used.",
        when=["Onboarding progress under the Stepper.", "Clip time used against the plan limit.", "Upload progress."],
        when_not=["Unknown duration: Spinner."],
        anatomy=["Track (`progress-bar.track`)", "Indicator (`progress-bar.indicator`)"],
        props=[P("value", "number", "—", True, "Current value."),
               P("max", "number", "100", False, "Maximum value."),
               P("label", "string", "—", True, "Accessible name ('Clip time used')."),
               P("valueText", "string", "—", False, "Readable value ('0:11 of 2:30') instead of a percentage.")],
        variants={}, states=["empty", "partial", "complete"],
        tokens=["progress-bar.track", "progress-bar.indicator", "progress-bar.height", "size.radius.pill"],
        interaction=["Not interactive; the indicator width animates with `motion.transition-fast`."],
        a11y=["Native `<progress>` with `aria-label` and `aria-valuetext`."],
        composition=["Stepper, ClipItem lists, upload screens."],
        antipatterns=["Using it for unknown durations.", "Showing it with no text nearby that states the value."],
        deps=[],
        example='<ProgressBar value={11} max={150} label="Clip time used" valueText="0:11 of 2:30" />',
        examples_bad='<div className="bar"><div style={{ width: "7%" }} /></div>',
    ),
    dict(
        name="Illustration", category="atom", status="stable", figma="54:353", since="1.1.0",
        purpose="Draws one of the Alora illustrations with theme colors.",
        when=["Auth background (auth-background).", "Empty states (surfers, nothing-reviewed)."],
        when_not=["Icons inside controls: Icon.", "Photos: an `<img>` with alt text."],
        anatomy=["SVG that uses `color.*` tokens, so it follows the theme"],
        props=[P("name", "'auth-background' | 'surfers' | 'nothing-reviewed'", "—", True, "Illustration."),
               P("label", "string", "—", False, "Makes the illustration meaningful (`role=img`).")],
        variants={"name": ["auth-background", "surfers", "nothing-reviewed"]}, states=["—"],
        tokens=["color.background.*", "color.text.brand", "color.text.highlight", "size.layout.illustration-small", "size.layout.illustration-medium"],
        interaction=["Not interactive."],
        a11y=["Decorative by default (`aria-hidden`)."],
        composition=["AuthTemplate background=illustrated, EmptyState illustration."],
        antipatterns=["Exporting illustrations as PNG: colors would not follow the theme."],
        deps=[],
        example='<Illustration name="nothing-reviewed" />',
        examples_bad='<img src="empty.png" />',
    ),
    # -------------------------------------------------------------- MOLECULES
    dict(
        name="FormField", category="molecule", status="stable", figma="13:54",
        purpose="Groups a field's Label, Input, helper text and error message.",
        when=["Any form field (log in, onboarding, profile)."],
        when_not=["Search: SearchField."],
        anatomy=["Label", "Input or Textarea", "Optional helper text", "Error message with icon"],
        props=[P("label", "string", "—", True, "Label text."),
               P("id", "string", "—", True, "Control id."),
               P("helperText", "string", "—", False, "Help below the field."),
               P("errorMessage", "string", "—", False, "When set, the field switches to the error state."),
               P("isRequired", "boolean", "false", False, "Required."),
               P("isDisabled", "boolean", "false", False, "Disabled."),
               P("children", "ReactElement<Input | Textarea>", "—", True, "The control.")],
        variants={}, states=["default", "error", "disabled"],
        tokens=["size.space.small", "typography.body-small", "color.text.tertiary", "color.feedback.danger.foreground"],
        interaction=["The error appears on blur or on submit, not while typing."],
        a11y=["Connects `aria-describedby` to the helper and error text.", "The error is announced with `role=alert` the first time."],
        composition=["Inside FormSection or the Modal Content slot."],
        antipatterns=["Showing helper text and an error at the same time.", "Error messages that do not say how to fix the problem."],
        deps=["Label", "Input", "Textarea", "Text", "Icon"],
        example='<FormField id="email" label="Email" errorMessage={error}>\n  <Input id="email" type="email" />\n</FormField>',
        examples_bad='<Label>Email</Label><Input /><span className="red">Error</span>',
    ),
    dict(
        name="SearchField", category="molecule", status="stable", figma="13:92",
        purpose="Search field with an icon and a clear button.",
        when=["Search surfers, clips or spots in long lists."],
        when_not=["Filters with a fixed set of values: TagChip."],
        anatomy=["Input with a search icon", "Clear button (visible when there is text)"],
        props=[P("value", "string", "—", True, "Search text."),
               P("onChange", "(value: string) => void", "—", True, "Change."),
               P("placeholder", "string", "'Search'", False, "What is being searched: 'Search surfers'."),
               P("onClear", "() => void", "—", False, "Clears and returns focus.")],
        variants={"filled": ["false", "true"]}, states=["default", "focus"],
        tokens=["input.*", "color.icon.secondary"],
        interaction=["Escape clears the text.", "Results are filtered with a 200ms debounce."],
        a11y=["`role=search` container; `type=search` Input with a hidden label.", "The clear button has `aria-label=\"Clear search\"`."],
        composition=["Above lists (Surfers)."],
        antipatterns=["Search without an accessible label."],
        deps=["Input", "Icon", "Button"],
        example='<SearchField value={q} onChange={setQ} placeholder="Search surfers" />',
        examples_bad='<Input placeholder="Search…" />',
    ),
    dict(
        name="ListItem", category="molecule", status="stable", figma="13:120",
        purpose="List row with three formats: person, definition or navigation.",
        when=["List of surfers (person).", "Account details (definition).", "Legal links (navigation)."],
        when_not=["Rich content with several actions: SubmissionCard."],
        anatomy=["person: Avatar + title + description + action", "definition: label + value + optional action", "navigation: title + chevron"],
        props=[P("type", "'person' | 'definition' | 'navigation'", "'definition'", False, "Format."),
               P("title", "string", "—", True, "Title or label."),
               P("description", "string", "—", False, "Description (person) or value (definition)."),
               P("avatarName", "string", "—", False, "person only."),
               P("avatarTone", "AvatarTone", "'brand'", False, "person only: avatar color, usually the plan."),
               P("badge", "{ label: string; tone: BadgeTone }", "—", False, "person only: plan Badge before the description."),
               P("action", "{ label: string; onPress: () => void; tone?: 'default' | 'danger' }", "—", False, "Action on the right."),
               P("href", "string", "—", False, "navigation: destination. person: the whole row links to the profile and shows a chevron."),
               P("hasDivider", "boolean", "true", False, "Bottom divider.")],
        variants={"type": ["person", "definition", "navigation"]}, states=["default", "hover (navigation)"],
        tokens=["size.space.large", "size.space.medium", "divider.color", "typography.overline", "typography.body-small", "typography.heading-small"],
        interaction=["navigation, and person with href: the whole row is clickable.", "definition actions are Links (danger for destructive ones)."],
        a11y=["Lists use `<ul>`; definition rows use `<dl>` with `<dt>`/`<dd>`."],
        composition=["DataList, surfer lists."],
        antipatterns=["Mixing types within the same list."],
        changes=['Added avatarTone, badge and linked person rows.', 'Definition row actions are now Links.'],
        deps=["Avatar", "Badge", "Heading", "Text", "Button", "Link", "Icon", "Divider"],
        example='<ListItem type="definition" title="PLAN RENEWS" description="26 sept 2026" action={{ label: "Cancel your plan", tone: "danger", onPress: openCancel }} />',
        examples_bad='<div className="row">…</div>',
    ),
    dict(
        name="TagChip", category="molecule", status="beta", figma="13:139",
        purpose="Selectable or removable chip.",
        when=["Filters (level, wave type), labels the user adds or removes."],
        when_not=["Static information: Tag or Badge."],
        anatomy=["Pill container", "Label", "Optional remove button"],
        props=[P("label", "string", "—", True, "Text."),
               P("isSelected", "boolean", "false", False, "Selected."),
               P("onToggle", "() => void", "—", False, "Selection."),
               P("onRemove", "() => void", "—", False, "Shows a remove button.")],
        variants={}, states=["default", "hover", "selected"],
        tokens=["tag.radius", "tag.padding-horizontal", "color.action.secondary.*", "color.background.brand-subtle", "color.border.brand", "color.text.brand"],
        interaction=["Clicking toggles; the remove button does not toggle."],
        a11y=["`<button aria-pressed>`; remove is a separate button with `aria-label=\"Remove {label}\"`."],
        composition=["Horizontal groups that wrap, with a `size.space.small` gap."],
        antipatterns=["Using TagChip for system states."],
        deps=["Text", "Icon"],
        example='<TagChip label="Advanced" isSelected onToggle={toggle} onRemove={remove} />',
        examples_bad='<Badge onClick={toggle}>Advanced</Badge>',
    ),
    dict(
        name="Stat", category="molecule", status="stable", figma="13:154",
        purpose="Shows a metric with its label and an optional trend.",
        when=["Queue summary (Pending, Reviewed) and plan summary (Cycle submissions, Renews)."],
        when_not=["Time series: chart (planned)."],
        anatomy=["Label", "Value (`typography.metric`)", "Optional trend (icon + text)"],
        props=[P("label", "string", "—", True, "What is measured."),
               P("value", "string | number", "—", True, "Formatted value."),
               P("trend", "{ direction: 'up' | 'down'; label: string }", "—", False, "Change."),
               P("caption", "string", "—", False, "Line under the label (“Paid on Oct 1”)."),
               P("variant", "'default' | 'featured' | 'compact'", "'default'", False, "featured: big centered total (earnings). compact: label and value on one row.")],
        variants={"trend": ["none", "up"], "variant": ["default", "featured", "compact"]}, states=["—"],
        tokens=["stat.background", "stat.label", "stat.value", "card.radius", "size.space.xl", "typography.metric", "color.feedback.success.foreground", "color.background.brand-subtle", "typography.display"],
        interaction=["Not interactive."],
        a11y=["Label and value in the same `<div role=group>` with `aria-label`.", "The trend is read as text."],
        composition=["Grid of stats that wraps at `size.layout.stat-min-width`."],
        antipatterns=["Trend shown only with color."],
        changes=['Added caption and the featured and compact variants.'],
        deps=["Text", "Icon"],
        example='<Stat label="Pending" value={3} />',
        examples_bad='<div className="stat"><b>3</b></div>',
    ),
    dict(
        name="Notification", category="molecule", status="stable", figma="13:209",
        purpose="Communicates a system message with a tone, an action and a dismiss button.",
        when=["Successful submission, approaching deadline, upload error, process info."],
        when_not=["Field errors: FormField.", "Blocking decisions: Modal."],
        anatomy=["Icon in a tinted container", "Title", "Description", "Optional action", "Optional dismiss"],
        props=[P("tone", "'info' | 'success' | 'warning' | 'danger'", "'info'", False, "Tone."),
               P("title", "string", "—", True, "Main message."),
               P("description", "string", "—", False, "Detail."),
               P("action", "{ label: string; onPress: () => void }", "—", False, "Action."),
               P("onDismiss", "() => void", "—", False, "Shows a dismiss button."),
               P("density", "'default' | 'compact'", "'default'", False, "compact: one line, title only (form errors such as “Incorrect email or password”).")],
        variants={"tone": ["info", "success", "warning", "danger"], "density": ["default", "compact"]}, states=["visible", "dismissed"],
        tokens=["notification.background", "notification.border", "notification.radius", "color.feedback.*", "typography.heading-small", "typography.body-small"],
        interaction=["info/success may auto-dismiss after 6s; warning/danger never do."],
        a11y=["info/success use `role=status`; danger uses `role=alert`.", "Dismiss is a button with `aria-label=\"Dismiss\"`."],
        composition=["Stacked in the top-right corner (`layer.toast`) or inline above the content."],
        antipatterns=["More than 3 visible notifications.", "Error messages that disappear on their own."],
        changes=['Added the compact density; danger uses the alert-circle icon; warning has a tinted background.'],
        deps=["Icon", "Heading", "Text", "Button"],
        example='<Notification tone="success" title="Submission sent" description="Your coach has 48h to review your clip." />',
        examples_bad='alert("Upload failed")',
    ),
    dict(
        name="Breadcrumb", category="molecule", status="beta", figma="13:210",
        purpose="Shows where the user is within a hierarchy.",
        when=["Detail views 3+ levels deep (Surfers › Surfer › Clip)."],
        when_not=["Top-level Sidebar views."],
        anatomy=["Links", "Chevron separators", "Current item"],
        props=[P("items", "Array<{ label: string; href?: string }>", "—", True, "The last item is the current page.")],
        variants={}, states=["—"],
        tokens=["color.text.brand", "color.text.primary", "color.icon.secondary", "typography.body-small", "size.space.small"],
        interaction=["Links navigate; the current item is not a link."],
        a11y=["`<nav aria-label=\"Breadcrumb\">` + `<ol>`; current item with `aria-current=page`."],
        composition=["Above PageHeader in detail views."],
        antipatterns=["Breadcrumb as a replacement for the Sidebar."],
        deps=["Text", "Icon"],
        example='<Breadcrumb items={[{ label: "Surfers", href: "/surfers" }, { label: "Alejandro García" }]} />',
        examples_bad='<p>Surfers / Alejandro</p>',
    ),
    dict(
        name="Pagination", category="molecule", status="beta", figma="13:221",
        purpose="Moves between pages of a long list.",
        when=["History with more than 20 reviews."],
        when_not=["Short lists or continuous feeds."],
        anatomy=["Previous", "Page status", "Next"],
        props=[P("page", "number", "—", True, "Current page (1-based)."),
               P("pageCount", "number", "—", True, "Total pages."),
               P("onPageChange", "(page: number) => void", "—", True, "Change.")],
        variants={}, states=["first", "middle", "last"],
        tokens=["button.*", "size.space.xs"],
        interaction=["Previous is disabled on the first page and Next on the last."],
        a11y=["`<nav aria-label=\"Pagination\">`; the page status is announced with `aria-live=polite`."],
        composition=["Below the list it paginates."],
        antipatterns=["Pagination with a single page."],
        deps=["Button", "Text"],
        example='<Pagination page={2} pageCount={8} onPageChange={setPage} />',
        examples_bad='<a>Next</a>',
    ),
    dict(
        name="NavigationItem", category="molecule", status="stable", figma="13:293",
        purpose="Main navigation entry with an icon and a label.",
        when=["Inside Sidebar."],
        when_not=["Actions: Button."],
        anatomy=["24px icon", "Label", "Bottom divider"],
        props=[P("label", "string", "—", True, "Destination."),
               P("icon", "IconName", "—", True, "Icon."),
               P("href", "string", "—", True, "URL."),
               P("isActive", "boolean", "false", False, "Current page.")],
        variants={}, states=["default", "hover", "active"],
        tokens=["navigation-item.*", "color.action.ghost.background-hover", "size.space.large"],
        interaction=["Hover tints the icon with the brand color."],
        a11y=["`<a>` with `aria-current=page` when active.", "Active state is shown by both text and icon color, not text color alone."],
        composition=["Only inside Sidebar."],
        antipatterns=["More than one active item at once."],
        deps=["Icon", "Text"],
        example='<NavigationItem label="Queue" icon="play-circle" href="/queue" isActive />',
        examples_bad='<div onClick={go}>Queue</div>',
    ),
    dict(
        name="OptionCard", category="molecule", status="stable", figma="62:124", since="1.1.0",
        purpose="Large selectable card for one choice among a few, with a title and an optional description.",
        when=["Onboarding answers: skill level, stance, goal, coaching approach.", "Choosing a plan or a profile (Coach or Surfer)."],
        when_not=["Many options or short labels: SegmentedControl or Radio.", "Several answers at once: Checkbox."],
        anatomy=["Card container (`option-card.*`)", "Optional radio indicator", "Title (`typography.heading-small`)", "Optional description (`typography.body-small`)"],
        props=[P("title", "string", "—", True, "Option name."),
               P("description", "string", "—", False, "One line that explains the option."),
               P("value", "string", "—", True, "Value sent to onChange."),
               P("name", "string", "—", True, "Group name, shared by every card in the group."),
               P("isSelected", "boolean", "false", False, "Selected."),
               P("hasIndicator", "boolean", "true", False, "Shows the radio circle. Without it the text is centered (stance)."),
               P("isDisabled", "boolean", "false", False, "Disabled."),
               P("onChange", "(value: string) => void", "—", False, "Selection.")],
        variants={"hasIndicator": ["true", "false"]}, states=["default", "hover", "focus", "selected", "disabled"],
        tokens=["option-card.background", "option-card.border", "option-card.background-selected", "option-card.border-selected", "option-card.radius", "radio.*", "size.space.large"],
        interaction=["Clicking anywhere on the card selects it.", "Arrow keys move between cards of the same group (native radio behavior)."],
        a11y=["A `<label>` around a native radio: the group needs a `<fieldset>` with a `<legend>` (the step question).", "Selection is shown by border, background and the indicator, not color alone."],
        composition=["Vertical stack with a `size.space.small` gap; two columns for short options (stance)."],
        antipatterns=["Mixing OptionCard and Checkbox in the same question.", "Navigating on select: let the user confirm with Continue."],
        deps=[],
        example='<OptionCard name="level" value="intermediate" title="Intermediate" description="I catch green waves and trim along them." isSelected={level === "intermediate"} onChange={setLevel} />',
        examples_bad='<div className={selected ? "card active" : "card"} onClick={select}>Intermediate</div>',
    ),
    dict(
        name="SegmentedControl", category="molecule", status="stable", figma="62:184", since="1.1.0",
        purpose="Row of mutually exclusive options shown side by side.",
        when=["Short choices: gender, board type, frequency.", "Switching a list filter with 2–5 options."],
        when_not=["Options that need a description: OptionCard.", "Several answers at once: TagChip."],
        anatomy=["Group container (`segmented-control.background`, border)", "Options (pill per option)", "Selected option fill (brand or highlight)"],
        props=[P("label", "string", "—", True, "Accessible name of the group ('Gender')."),
               P("options", "Array<{ label: string; value: string }>", "—", True, "2–6 options."),
               P("value", "string", "—", False, "Selected value."),
               P("onChange", "(value: string) => void", "—", False, "Selection."),
               P("tone", "'brand' | 'highlight'", "'brand'", False, "Color of the selected option."),
               P("layout", "'fill' | 'hug'", "'fill'", False, "fill shares the width; hug sizes pills to their text and wraps."),
               P("size", "'small' | 'medium'", "'medium'", False, "Height.")],
        variants={"tone": ["brand", "highlight"], "layout": ["fill", "hug"], "size": ["small", "medium"]}, states=["default", "hover", "focus", "selected"],
        tokens=["segmented-control.background", "segmented-control.border", "segmented-control.selected-brand", "segmented-control.on-selected-brand", "segmented-control.selected-highlight", "segmented-control.on-selected-highlight", "size.radius.pill", "typography.label"],
        interaction=["Click selects; arrow keys move and select (radio group)."],
        a11y=["`role=radiogroup` with `aria-label`; each option is a native radio.", "The selected option has a filled background and higher-contrast text."],
        composition=["Inside FormField-like groups in onboarding and Edit profile."],
        antipatterns=["More than 6 options.", "Using it to trigger actions."],
        deps=[],
        example='<SegmentedControl label="Gender" tone="highlight" options={[{ label: "Male", value: "male" }, { label: "Female", value: "female" }, { label: "Other", value: "other" }]} value={gender} onChange={setGender} />',
        examples_bad='<div>{options.map(o => <button className={o === v ? "on" : ""}>{o}</button>)}</div>',
    ),
    dict(
        name="Stepper", category="molecule", status="stable", figma="62:242", since="1.1.0",
        purpose="Shows where the user is in a multi-step flow.",
        when=["Surfer onboarding (5 steps).", "Any form split into ordered steps."],
        when_not=["Free navigation between sections: tabs or Sidebar.", "One-step forms."],
        anatomy=["Numbered markers (done with a check, current filled, upcoming outlined)", "ProgressBar under the markers"],
        props=[P("steps", "string[]", "—", True, "Step names; read by screen readers."),
               P("currentStep", "number", "—", True, "Index of the current step, from 0.")],
        variants={}, states=["first", "middle", "last"],
        tokens=["stepper.step-background", "stepper.step-foreground", "stepper.step-current", "stepper.step-on-current", "progress-bar.*", "size.layout.icon-tile-small"],
        interaction=["Not interactive: steps change with Continue and Back."],
        a11y=["`<nav aria-label=\"Progress\">` with an ordered list; the current step has `aria-current=step`.", "Each marker carries the step name (visually hidden) and its state."],
        composition=["Top of each onboarding step, above the question."],
        antipatterns=["Clickable markers that skip validation."],
        deps=["ProgressBar", "Icon"],
        example='<Stepper steps={["Skill level", "Stance", "Goal", "Approach", "About you"]} currentStep={1} />',
        examples_bad='<p>Step 2/5</p>',
    ),
    dict(
        name="Dropzone", category="molecule", status="stable", figma="62:269", since="1.1.0",
        purpose="Area to pick or drop files for upload.",
        when=["New submission: add surf clips.", "Any upload of videos or images."],
        when_not=["One small file in a form: a file Input (planned)."],
        anatomy=["Dashed container (`dropzone.*`)", "IconTile (plus, or close on error)", "Label", "Hint (formats and limits)"],
        props=[P("label", "string", "—", True, "Call to action ('Tap to add surf clips')."),
               P("hint", "string", "—", False, "Formats and limits ('MP4 or MOV · Max 2:30 per clip')."),
               P("accept", "string", "—", False, "Accepted types ('video/*')."),
               P("isMultiple", "boolean", "false", False, "Allows several files."),
               P("errorMessage", "string", "—", False, "Failed state: replaces the label with this message."),
               P("isDisabled", "boolean", "false", False, "Disabled."),
               P("onFiles", "(files: File[]) => void", "—", False, "Files picked or dropped.")],
        variants={"state": ["default", "error"]}, states=["default", "hover", "drag-over", "focus", "error", "disabled"],
        tokens=["dropzone.background", "dropzone.border", "dropzone.background-error", "dropzone.border-error", "icon-tile.*", "size.border.default", "card.radius"],
        interaction=["Click or Enter opens the file picker; drag over highlights the area; drop calls onFiles."],
        a11y=["A visually hidden native file input inside a `<label>`, so it works with keyboard and screen readers.", "The hint is linked with `aria-describedby`; in the error state the message replaces the label, so it becomes the accessible name, and the input is `aria-invalid`."],
        composition=["New submission screen above the ClipItem list."],
        antipatterns=["Drag and drop as the only way to add files."],
        deps=["IconTile"],
        example='<Dropzone label="Tap to add surf clips" hint="MP4 or MOV · Max 2:30 per clip" accept="video/*" isMultiple onFiles={addClips} />',
        examples_bad='<div onDrop={drop}>Drop here</div>',
    ),
    dict(
        name="ClipItem", category="molecule", status="stable", figma="62:320", since="1.1.0",
        purpose="Row for one video clip: thumbnail, title, facts and a light action.",
        when=["Clips added to a new submission.", "Clips inside a submission in History or the coach review."],
        when_not=["A whole submission with status and deadline: SubmissionCard.", "A delivered review: ReviewCard."],
        anatomy=["Thumbnail (optional play button and status Badge solid)", "Title", "Meta (duration, size)", "Optional details", "Optional action (Link)"],
        props=[P("title", "string", "—", True, "Clip name."),
               P("meta", "string", "—", False, "Short facts ('1 clip · 0:11')."),
               P("details", "ReactNode", "—", False, "Extra lines (coach, expected date)."),
               P("thumbnailSrc", "string", "—", False, "Thumbnail image; a dark placeholder shows when missing."),
               P("thumbnailAlt", "string", "''", False, "Alt text when the thumbnail is meaningful."),
               P("status", "{ label: string; tone: 'pending' | 'in-review' | 'review-ready' | 'overdue' }", "—", False, "Status shown on the thumbnail."),
               P("isPlayable", "boolean", "false", False, "Shows a play icon on the thumbnail."),
               P("action", "{ label: string; icon?: IconName; tone?: 'brand' | 'danger'; onPress: () => void }", "—", False, "Row action ('Delete clip')."),
               P("size", "'small' | 'medium'", "'medium'", False, "Thumbnail 56 or 94 px tall (16:9).")],
        variants={"size": ["small", "medium"]}, states=["default", "with-status", "with-action"],
        tokens=["size.layout.thumbnail-width", "size.layout.thumbnail-height", "color.media.background", "color.media.scrim", "card.radius", "color.status.*.solid", "typography.heading-small", "typography.body-small"],
        interaction=["Only the action is interactive."],
        a11y=["Decorative thumbnail by default (`alt=\"\"`).", "The status is real text inside the Badge."],
        composition=["Stacked with Dividers inside a card, under Dropzone or inside SubmissionCard."],
        antipatterns=["A whole clickable row with a nested action."],
        deps=["Badge", "Link", "Icon"],
        example='<ClipItem title="Surf clip" meta="1 clip · 0:11" isPlayable action={{ label: "Delete clip", icon: "trash", tone: "danger", onPress: remove }} />',
        examples_bad='<div className="clip"><img src={t} /><a className="red">Delete</a></div>',
    ),
    dict(
        name="SummaryRow", category="molecule", status="stable", figma="62:324", since="1.1.0",
        purpose="Labelled fact with a leading icon, used to summarize what happened.",
        when=["Submission sent: clips, coach, expected review.", "Short receipts and confirmations."],
        when_not=["Editable data or long lists: DataList."],
        anatomy=["IconTile medium", "Label (`typography.overline`)", "Value (`typography.body-medium`)"],
        props=[P("icon", "IconName", "—", True, "Icon."),
               P("label", "string", "—", True, "What the value is."),
               P("value", "ReactNode", "—", True, "The fact.")],
        variants={}, states=["—"],
        tokens=["icon-tile.*", "typography.overline", "typography.body-medium", "color.text.tertiary", "color.text.primary", "size.space.medium"],
        interaction=["Not interactive."],
        a11y=["`<dl>` with `<dt>` label and `<dd>` value; the icon is decorative."],
        composition=["Stacked inside ResultState."],
        antipatterns=["Using SummaryRow for actions."],
        deps=["IconTile"],
        example='<SummaryRow icon="video" label="Clips" value="2 clips · 1:46" />',
        examples_bad='<p><Icon name="video" /> Clips: 2</p>',
    ),
    dict(
        name="StatGroup", category="molecule", status="stable", figma="62:371", since="1.1.0",
        purpose="Two to four small metrics side by side inside one card.",
        when=["Plan usage (Submissions left, Clip time), Surfer profile numbers, coach earnings summary."],
        when_not=["A single highlighted metric: Stat featured.", "Metrics with trends: Stat."],
        anatomy=["Row of items: value (`typography.metric`) over label (`typography.overline`)", "Vertical dividers between items"],
        props=[P("items", "Array<{ label: string; value: string | number; tone?: 'primary' | 'brand' | 'highlight' }>", "—", True, "2–4 metrics."),
               P("size", "'small' | 'medium'", "'medium'", False, "Value size.")],
        variants={"size": ["small", "medium"]}, states=["—"],
        tokens=["stat.background", "stat.label", "stat.value", "color.text.brand", "color.text.highlight", "divider.color", "typography.metric"],
        interaction=["Not interactive."],
        a11y=["`<dl>`: each label is a `<dt>` read before its value, even though the value is shown on top."],
        composition=["Inside a card, ResultState or under a SectionHeader."],
        antipatterns=["More than four items; use a DataList."],
        deps=[],
        example='<StatGroup items={[{ label: "Submissions left", value: 3, tone: "brand" }, { label: "Clip time", value: "2:30" }]} />',
        examples_bad='<div className="stats"><b>3</b> left</div>',
    ),
    dict(
        name="SectionHeader", category="molecule", status="stable", figma="62:417", since="1.1.0",
        purpose="Title of a simple page or of a section inside it, with an optional icon, subtitle and action.",
        when=["Assigned surfers, Your history, Account & Billing, Weekly availability."],
        when_not=["A greeting header with avatar and plan: PageHeader.", "A detail screen with a back button: TopBar."],
        anatomy=["Optional IconTile", "Heading", "Optional subtitle", "Optional action on the right"],
        props=[P("title", "string", "—", True, "Section name."),
               P("subtitle", "ReactNode", "—", False, "Count or explanation; accepts `<strong>`."),
               P("icon", "IconName", "—", False, "Leading icon in a tile."),
               P("size", "'small' | 'large'", "'large'", False, "large for page sections, small for groups inside a card."),
               P("as", "'h1' | 'h2' | 'h3'", "h1 when large, h2 when small", False, "Heading level."),
               P("action", "ReactNode", "—", False, "Link or Button on the right."),
               P("id", "string", "—", False, "id of the heading, for `aria-labelledby`.")],
        variants={"size": ["small", "large"]}, states=["—"],
        tokens=["typography.heading-large", "typography.heading-small", "typography.body-small", "color.text.secondary", "icon-tile.*", "size.space.medium"],
        interaction=["Only the action is interactive."],
        a11y=["Real heading element; keep levels in order."],
        composition=["First element of a section; DataList and AvailabilityGrid sit under it."],
        antipatterns=["Bold Text pretending to be a title."],
        deps=["Heading", "IconTile"],
        example='<SectionHeader title="Assigned surfers" subtitle="12 surfers" action={<Link href="/surfers">See all</Link>} />',
        examples_bad='<b>Assigned surfers</b>',
    ),
    dict(
        name="PeriodStepper", category="molecule", status="stable", figma="62:421", since="1.1.0",
        purpose="Moves backward and forward between periods (weeks, pay periods).",
        when=["Coach schedule week, earnings pay period."],
        when_not=["Picking an arbitrary date: date picker (planned).", "Pages of a list: Pagination."],
        anatomy=["Previous IconButton", "Caption + current period", "Next IconButton"],
        props=[P("label", "string", "—", True, "Caption ('Pay period')."),
               P("value", "string", "—", True, "Current period ('Sep 15 - Sep 30')."),
               P("onPrevious", "() => void", "—", False, "Previous period."),
               P("onNext", "() => void", "—", False, "Next period."),
               P("isPreviousDisabled", "boolean", "false", False, "No earlier period."),
               P("isNextDisabled", "boolean", "false", False, "No later period.")],
        variants={}, states=["default", "first", "last"],
        tokens=["button.secondary.*", "typography.overline", "typography.heading-small", "size.space.small"],
        interaction=["Buttons change the period; the value is announced politely."],
        a11y=["Buttons are labelled 'Previous {label}' and 'Next {label}'.", "`role=group` named by the caption; the value lives in an `aria-live=polite` region."],
        composition=["Above the data that belongs to the period (AvailabilityGrid, earnings)."],
        antipatterns=["Arrows without labels."],
        deps=["IconButton"],
        example='<PeriodStepper label="Pay period" value="Sep 15 - Sep 30" onPrevious={prev} onNext={next} isNextDisabled />',
        examples_bad='<span>‹ Sep 15 - Sep 30 ›</span>',
    ),
    # -------------------------------------------------------------- ORGANISMS
    dict(
        name="Sidebar", category="organism", status="stable", figma="14:84",
        purpose="Fixed main navigation on desktop.",
        when=["Every authenticated Coach and Surfer view at ≥ 1024px."],
        when_not=["Mobile: bottom NavigationBar (planned)."],
        anatomy=["List of NavigationItem", "Logo at the bottom"],
        props=[P("product", "'coach' | 'surfer'", "—", True, "Sets the default items: Coach Queue, Surfers, Schedule, Profile; Surfer Dashboard, History, Profile."),
               P("activeHref", "string", "—", True, "Active item."),
               P("items", "Array<NavigationItemProps>", "from product", False, "Overrides the items (max. 5).")],
        variants={"product": ["coach", "surfer"]}, states=["—"],
        tokens=["sidebar.background", "sidebar.width", "navigation-item.*"],
        interaction=["Stays fixed while scrolling (`layer.sticky`)."],
        a11y=["`<nav aria-label=\"Main\">`; a single `aria-current`."],
        composition=["Items slot (max. 5) + Logo.", "Not customizable: width, background, logo position."],
        antipatterns=["Adding actions (buttons) to the Sidebar."],
        changes=['Default items follow the redesign (Coach: Queue, Surfers, Schedule, Profile; Surfer: Dashboard, History, Profile) and the Logo sits at the bottom.'],
        deps=["NavigationItem", "Logo"],
        example='<Sidebar product="coach" activeHref="/" />',
        examples_bad='<Sidebar style={{ width: 200 }} />',
    ),
    dict(
        name="PageHeader", category="organism", status="stable", figma="14:116",
        purpose="Header of each view with a title, subtitle and actions.",
        when=["First section of every view inside DashboardTemplate."],
        when_not=["Inner section titles: Heading medium."],
        anatomy=["Title (Heading, h1)", "Optional subtitle", "Actions slot (max. 2)"],
        props=[P("title", "string", "—", True, "Greeting or title."),
               P("subtitle", "string", "—", False, "Supporting text."),
               P("actions", "ReactNode", "—", False, "Tag, Avatar or Button (max. 2)."),
               P("size", "'display' | 'large'", "'display'", False, "large for secondary dashboards (Schedule, Surfers).")],
        variants={"context": ["coach", "surfer"], "size": ["display", "large"]}, states=["—"],
        tokens=["typography.display", "typography.heading-large", "color.text.brand", "size.space.small", "size.space.medium", "size.layout.content-width"],
        interaction=["Not interactive; its actions are."],
        a11y=["The only h1 in the view."],
        composition=["DashboardTemplate Header slot."],
        antipatterns=["More than two actions; use a menu."],
        changes=['Added the large size.'],
        deps=["Heading", "Text", "Tag", "Avatar"],
        example='<PageHeader title="Welcome, Alejandro" subtitle="Connect with your surfers" actions={<Avatar name="Coach" tone="elite" />} />',
        examples_bad='<h1 style={{ fontSize: 40 }}>Welcome</h1>',
    ),
    dict(
        name="SubmissionCard", category="organism", status="stable", figma="14:223",
        purpose="Summarizes a clip submitted for review and its main action.",
        when=["Coach queue, surfer submission list."],
        when_not=["A review already delivered in History: ReviewCard."],
        anatomy=["Header: Avatar + name + plan Badge + status Badge (+ optional status text)", "Clip title (h3) + date + metadata", "Optional note with its caption (From surfer)", "Footer: deadline Tag or footnote + secondary and primary small Buttons"],
        props=[P("surfer", "{ name: string; plan: 'pay-as-you-go' | 'elite' | 'progression' | 'session' | 'performance' }", "—", False, "Who submitted it. Leave it out on the surfer side."),
               P("status", "'pending' | 'in-review' | 'review-ready' | 'overdue'", "—", True, "State."),
               P("statusText", "string", "—", False, "Badge text when it differs from the default (“Waiting for review”)."),
               P("clipTitle", "string", "—", True, "Maneuver."),
               P("submittedAt", "string", "—", True, "Formatted date."),
               P("meta", "string", "—", False, "Stance · level · spot."),
               P("note", "string", "—", False, "Message from the surfer or the coach."),
               P("noteLabel", "string", "'From surfer'", False, "Caption of the note."),
               P("deadline", "{ label: string; tone: 'on-track' | 'due-soon' | 'overdue' }", "—", False, "Deadline."),
               P("footnote", "string", "—", False, "Small line with a video icon when there is no deadline (“2 clips · 1:46”)."),
               P("action", "{ label: string; icon?: IconName; onPress: () => void }", "—", True, "Main action."),
               P("secondaryAction", "{ label: string; icon?: IconName; onPress: () => void }", "—", False, "Second action, secondary style.")],
        variants={"deadline": ["on-track", "due-soon", "overdue"]}, states=["—"],
        tokens=["card.background", "card.border", "card.radius", "card.padding", "card.gap", "color.background.surface-sunken", "color.plan.*", "typography.overline", "size.layout.content-width"],
        interaction=["Only the button is interactive; the whole card is not clickable."],
        a11y=["`<article>` with the title as an h3 and `aria-labelledby`."],
        composition=["In a list: a column with a `size.space.large` gap.", "Customizable: text, tones and action. Not customizable: block order."],
        antipatterns=["Two primary buttons in the card.", "Hiding the status."],
        changes=['The surfer and the deadline are optional; added statusText, noteLabel, footnote and secondaryAction; the note is a captioned quote; actions are small.'],
        deps=["Avatar", "Heading", "Text", "Badge", "Tag", "Button"],
        example='<SubmissionCard surfer={{ name: "Khata Kraiwan", plan: "elite" }} status="in-review" clipTitle="Frontside snap" submittedAt="Aug 31, 2026, 18:01" deadline={{ label: "1h 9m left", tone: "due-soon" }} action={{ label: "View & Download", icon: "eye", onPress }} />',
        examples_bad='<Card><b>Frontside snap</b><button className="blue">View</button></Card>',
    ),
    dict(
        name="DataList", category="organism", status="stable", figma="14:224",
        purpose="Read-only data section with a title and definition rows.",
        when=["Account & Billing, Surf Profile, Legal."],
        when_not=["Comparable tabular data: DataTable (planned)."],
        anatomy=["Title with icon (Heading small)", "Card with ListItem type=definition or navigation"],
        props=[P("title", "string", "—", False, "Section title. Leave it out when a SectionHeader already titles the section."),
               P("icon", "IconName", "—", False, "Title icon."),
               P("items", "Array<ListItemProps>", "—", True, "Rows."),
               P("layout", "'stacked' | 'inline'", "'stacked'", False, "inline puts label and value on one row."),
               P("isStriped", "boolean", "false", False, "Alternating row backgrounds, no dividers (Surf profile).")],
        variants={"layout": ["stacked", "inline"], "isStriped": ["false", "true"]}, states=["—"],
        tokens=["card.background", "card.border", "card.radius", "color.background.brand-subtle", "color.background.surface", "size.space.medium"],
        interaction=["Row actions are the only interactive elements."],
        a11y=["`<section aria-labelledby>` with an `<h2>` and `<dl>` rows."],
        composition=["Stack sections with a `size.space.xl` gap."],
        antipatterns=["Mixing in editable fields: use FormSection."],
        changes=['Title is optional; added the inline layout and striped rows.'],
        deps=["ListItem", "Heading", "Icon"],
        example='<DataList title="Account & Billing" icon="user" items={rows} />',
        examples_bad='<table>…</table>',
    ),
    dict(
        name="EmptyState", category="organism", status="stable", figma="14:277",
        purpose="Explains why an area is empty and offers the next action.",
        when=["Empty queue, empty history, no surfers."],
        when_not=["Errors: danger Notification."],
        anatomy=["Decorative icon or Illustration", "Optional title", "Message", "Optional hint", "Optional action (Button)"],
        props=[P("title", "string", "—", False, "Short headline (“Nothing reviewed yet”)."),
               P("message", "string", "—", True, "Current state in the user's language."),
               P("hint", "string", "—", False, "Small line with the next step."),
               P("icon", "IconName", "'info'", False, "Icon."),
               P("illustration", "IllustrationName", "—", False, "Illustration instead of the icon."),
               P("variant", "'card' | 'inline'", "'card'", False, "inline: no card, left aligned, inside another section."),
               P("action", "{ label: string; icon?: IconName; variant?: 'primary' | 'secondary'; onPress: () => void }", "—", False, "Next step.")],
        variants={"action": ["false", "true"], "variant": ["card", "inline"]}, states=["—"],
        tokens=["card.background", "card.radius", "color.background.canvas", "color.text.tertiary", "size.space.xl"],
        interaction=["Only the action is interactive."],
        a11y=["Icon is `aria-hidden`; the message is real text."],
        composition=["Takes the place of the empty list."],
        antipatterns=["Messages that blame the user."],
        changes=['Added title, hint, illustration, the inline variant and the action variant.'],
        deps=["Icon", "Illustration", "Text", "Button"],
        example='<EmptyState message="No submissions waiting for review." />',
        examples_bad='<p>Nothing here</p>',
    ),
    dict(
        name="Modal", category="organism", status="stable", figma="14:348",
        purpose="Dialog for a decision or short task that interrupts the flow.",
        when=["Cancel a plan, request a coach change, confirm destructive actions."],
        when_not=["Non-blocking information: Notification.", "Long forms: a page of their own."],
        anatomy=["Optional IconTile (centered layout)", "Title + close button", "Description", "Content slot", "Footer: secondary + primary action (stacked at full width when centered)"],
        props=[P("isOpen", "boolean", "—", True, "Visibility."),
               P("title", "string", "—", True, "Title."),
               P("description", "string", "—", False, "Context."),
               P("tone", "'default' | 'danger'", "'default'", False, "danger uses a danger Button."),
               P("icon", "IconName", "—", False, "Centers the dialog under a large IconTile (Cancel your plan?)."),
               P("primaryAction", "{ label: string; onPress: () => void }", "—", True, "Main action."),
               P("secondaryAction", "{ label: string; onPress: () => void }", "—", False, "Cancel."),
               P("onClose", "() => void", "—", True, "Close (X, Escape, overlay)."),
               P("children", "ReactNode", "—", False, "Content slot.")],
        variants={"tone": ["default", "danger"], "icon": ["false", "true"]}, states=["open", "closed"],
        tokens=["modal.background", "modal.overlay", "modal.radius", "modal.padding", "modal.shadow", "layer.modal", "motion.transition-enter"],
        interaction=["Enters with `motion.transition-enter`; Escape and the overlay close it."],
        a11y=["Native `<dialog>` opened with `showModal()` and `aria-labelledby` pointing to the title.", "Focus is trapped and returns to the trigger on close.", "Initial focus goes to the first field, or to the secondary action when tone is danger."],
        composition=["The Content slot accepts FormField, Text and short lists."],
        antipatterns=["Chained modals.", "A modal with no way to close it."],
        changes=['Added the icon prop and its centered layout.'],
        deps=["Heading", "Text", "Button", "Icon", "IconTile", "FormField"],
        example='<Modal isOpen tone="danger" title="Cancel your plan?" primaryAction={{ label: "Cancel plan", onPress: cancel }} secondaryAction={{ label: "Keep my plan", onPress: close }} onClose={close} />',
        examples_bad='<div className="popup" style={{ zIndex: 9999 }}>…</div>',
    ),
    dict(
        name="FormSection", category="organism", status="stable", figma="14:349",
        purpose="Complete form with fields and actions.",
        when=["Log in, Create account, onboarding steps, edit profile."],
        when_not=["A single inline field: FormField."],
        anatomy=["Error summary (Notification) when there is more than one error", "Stacked FormFields", "Full-width primary action", "Optional ghost secondary action"],
        props=[P("onSubmit", "(event: FormEvent) => void", "—", True, "Submit."),
               P("children", "ReactNode", "—", True, "FormFields."),
               P("primaryAction", "{ label: string; icon?: IconName; isLoading?: boolean }", "—", True, "Submit."),
               P("secondaryAction", "{ label: string; onPress: () => void }", "—", False, "Alternative."),
               P("errorSummary", "string[]", "—", False, "Summary shown when there is more than one error.")],
        variants={}, states=["default", "submitting", "error"],
        tokens=["card.*", "size.layout.form-width", "size.space.large", "size.space.medium"],
        interaction=["Enter submits; the button shows its loading state while submitting."],
        a11y=["`<form noValidate>`; the error summary uses `role=alert` and focus goes to the first error."],
        composition=["AuthTemplate Form slot or the content column."],
        antipatterns=["Two primary actions.", "Validating while the user types."],
        deps=["FormField", "Button", "Notification"],
        example='<FormSection onSubmit={login} primaryAction={{ label: "Login", icon: "log-in" }} secondaryAction={{ label: "Create new account", onPress: goSignup }}>…</FormSection>',
        examples_bad='<form><input/><input/><button>Go</button></form>',
    ),
    dict(
        name="TopBar", category="organism", status="stable", figma="63:229", since="1.1.0",
        purpose="Header of a detail or task screen with a back button and a title.",
        when=["New submission, Edit profile, Change coach, a surfer detail, a review."],
        when_not=["Top-level views reached from the Sidebar: PageHeader or SectionHeader."],
        anatomy=["Back IconButton", "Title (Heading medium, h1)", "Optional actions on the right", "Bottom border (`top-bar.border`)"],
        props=[P("title", "string", "—", True, "Screen title."),
               P("onBack", "() => void", "—", False, "Shows the back button."),
               P("backLabel", "string", "'Back'", False, "Accessible name of the back button."),
               P("actions", "ReactNode", "—", False, "Up to two buttons or links.")],
        variants={"back": ["true", "false"]}, states=["—"],
        tokens=["top-bar.background", "top-bar.border", "typography.heading-medium", "size.space.medium", "size.layout.control-height"],
        interaction=["The back button returns to the previous screen."],
        a11y=["`<header>` with the only h1 of the screen.", "The back button has an accessible name."],
        composition=["First element inside DashboardTemplate (narrow) or a full-screen flow."],
        antipatterns=["A back button that loses unsaved changes without asking."],
        deps=["IconButton", "Heading"],
        example='<TopBar title="New submission" onBack={goBack} />',
        examples_bad='<div><a href="..">‹</a> New submission</div>',
    ),
    dict(
        name="ResultState", category="organism", status="stable", figma="63:338", since="1.1.0",
        purpose="Full-screen outcome of a task: success with a summary, or failure with a way to retry.",
        when=["Submission sent, Review sent, Account created.", "Submission failed, Upload failed."],
        when_not=["Small confirmations that do not leave the screen: Notification.", "Empty lists: EmptyState."],
        anatomy=["IconTile circle with halo (check on solid, or alert on danger)", "Title", "Description", "Optional summary slot (SummaryRow, StatGroup)", "Optional hint", "Primary and secondary full-width Buttons"],
        props=[P("tone", "'success' | 'danger'", "—", True, "Outcome."),
               P("title", "string", "—", True, "What happened ('Submission sent!')."),
               P("description", "ReactNode", "—", False, "Next steps."),
               P("hint", "string", "—", False, "Small line under the description."),
               P("children", "ReactNode", "—", False, "Summary of what happened."),
               P("primaryAction", "{ label: string; onPress: () => void }", "—", True, "Main next step ('Back to home', 'Try again')."),
               P("secondaryAction", "{ label: string; onPress: () => void }", "—", False, "Alternative.")],
        variants={"tone": ["success", "danger"]}, states=["—"],
        tokens=["icon-tile.*", "result-state.halo-success", "result-state.halo-danger", "typography.display", "typography.heading-large", "size.layout.form-width", "size.space.xl"],
        interaction=["Only the buttons are interactive."],
        a11y=["The title is the h1 of the screen; the screen that shows the result moves focus to it so the outcome is announced.", "The icon is decorative: the title states the outcome."],
        composition=["Centered in AuthTemplate or in the narrow DashboardTemplate column."],
        antipatterns=["A success screen with no way forward.", "Error results that do not say how to fix it."],
        deps=["IconTile", "Heading", "Text", "Button"],
        example='<ResultState tone="success" title="Submission sent!" description="Your coach will review your clips." primaryAction={{ label: "Back to home", onPress: goHome }}><SummaryRow icon="video" label="Clips" value="2 clips · 1:46" /></ResultState>',
        examples_bad='<div><h1>Done</h1></div>',
    ),
    dict(
        name="ReviewCard", category="organism", status="stable", figma="63:400", since="1.1.0",
        purpose="Delivered review in History, collapsed to a summary and expanded to show the coach note.",
        when=["Surfer History: each reviewed submission."],
        when_not=["Submissions still waiting: SubmissionCard."],
        anatomy=["Toggle row: play IconTile, clip title, dates, status Badge, chevron", "Panel: coach IconTile initial, coach name, note, primary Button"],
        props=[P("clipTitle", "string", "—", True, "Clip or submission title."),
               P("submittedAt", "string", "—", True, "Submission date."),
               P("reviewedAt", "string", "—", True, "Review date."),
               P("statusLabel", "string", "'Reviewed'", False, "Badge text."),
               P("coach", "{ name: string }", "—", True, "Coach who reviewed it."),
               P("note", "string", "—", True, "Coach summary."),
               P("action", "{ label: string; icon?: IconName; onPress: () => void }", "—", True, "Main action ('Watch review')."),
               P("isExpanded", "boolean", "—", False, "Controlled open state."),
               P("defaultExpanded", "boolean", "false", False, "Initial state when uncontrolled."),
               P("onToggle", "(isExpanded: boolean) => void", "—", False, "Toggle callback.")],
        variants={"expanded": ["false", "true"]}, states=["collapsed", "expanded", "hover", "focus"],
        tokens=["card.*", "icon-tile.*", "color.action.highlight.*", "typography.heading-small", "typography.body-small", "motion.transition-fast"],
        interaction=["Clicking the row, Enter or Space toggles the panel."],
        a11y=["Disclosure pattern: the toggle is a `<button aria-expanded aria-controls>` inside the h3.", "The collapsed panel is `hidden`, so it leaves the tab order."],
        composition=["Stacked list in History with a `size.space.medium` gap."],
        antipatterns=["Nesting links inside the toggle button."],
        deps=["IconTile", "Badge", "Button", "Icon", "Text"],
        example='<ReviewCard clipTitle="Frontside snap" submittedAt="Sep 2" reviewedAt="Sep 3" coach={{ name: "Alejandro" }} note="Great speed, open your shoulders earlier." action={{ label: "Watch review", icon: "play-circle", onPress: open }} />',
        examples_bad='<details><summary>Frontside snap</summary>…</details>',
    ),
    dict(
        name="VideoPlayer", category="organism", status="stable", figma="63:446", since="1.1.0",
        purpose="Plays a surf clip with Alora controls.",
        when=["Coach review screen, surfer review detail, clip preview."],
        when_not=["Thumbnails in lists: ClipItem."],
        anatomy=["Video area (`video-player.background`)", "Central play button", "Control bar: play/pause, timeline, time, mute, full screen"],
        props=[P("src", "string", "—", True, "Video URL."),
               P("title", "string", "—", True, "Accessible name (clip title)."),
               P("poster", "string", "—", False, "Image before playing.")],
        variants={}, states=["paused", "playing", "muted", "focus"],
        tokens=["video-player.background", "video-player.foreground", "video-player.track", "video-player.progress", "video-player.scrim", "card.radius", "size.layout.control-height-small"],
        interaction=["Space/Enter on the play button toggles playback.", "The timeline is a range input: arrows seek, Home and End jump."],
        a11y=["`<figure aria-label>` around a native `<video>`.", "Every control is a labelled button; mute uses `aria-pressed`.", "The timeline announces the time as 'm:ss of m:ss'."],
        composition=["Top of the review screen, full width of the content column."],
        antipatterns=["Autoplay with sound.", "Custom controls without keyboard support."],
        deps=["Icon"],
        example='<VideoPlayer src={clip.url} title="Frontside snap" poster={clip.thumbnail} />',
        examples_bad='<video src={url} autoPlay />',
    ),
    dict(
        name="AvailabilityGrid", category="organism", status="stable", figma="63:450", since="1.1.0",
        purpose="Weekly grid where a coach marks the hours they are available.",
        when=["Coach Schedule: weekly availability."],
        when_not=["Picking one date or time: date or time picker (planned)."],
        anatomy=["Day header row", "Hour column", "Toggle cells (`availability-grid.*`)", "Footer: legend + actions"],
        props=[P("label", "string", "—", True, "Accessible name ('Weekly availability')."),
               P("value", "string[]", "—", True, "Selected slots, as `slotId(day, hour)`."),
               P("onChange", "(value: string[]) => void", "—", True, "New selection."),
               P("days", "Array<{ short: string; long: string }>", "Mon–Sun", False, "Columns."),
               P("hours", "number[]", "6–21", False, "Start hours of the rows, 24-hour clock."),
               P("actions", "ReactNode", "—", False, "Footer buttons (Save availability, Clear all)."),
               P("legend", "{ selected: string; unselected: string }", "Available / Unavailable", False, "Legend texts.")],
        variants={}, states=["default", "hover", "focus", "selected"],
        tokens=["availability-grid.cell", "availability-grid.cell-alternate", "availability-grid.cell-selected", "availability-grid.line", "availability-grid.header", "typography.overline", "typography.caption"],
        interaction=["Click toggles a cell; dragging paints every cell it crosses with the first cell's new state.", "Arrow keys move between cells, Home and End jump in a row, Enter or Space toggles."],
        a11y=["`role=grid` table; each cell is a `<button aria-pressed>` named 'Monday 9:00'.", "Roving tabindex: one Tab stop for the whole grid.", "Selected cells change fill, not just color hue, and the legend explains them."],
        composition=["Under a SectionHeader and a PeriodStepper in Schedule."],
        antipatterns=["Saving on every click: keep an explicit Save action."],
        deps=[],
        example='<AvailabilityGrid label="Weekly availability" value={slots} onChange={setSlots} actions={<Button onPress={save}>Save availability</Button>} />',
        examples_bad='<table>{hours.map(h => <tr><td onClick={…} /></tr>)}</table>',
    ),
]
