"""Single source for component documentation. build_docs.py turns it into
*.docs.md, *.examples.md, *.tokens.json and MANIFEST.json.

Every field is required unless marked optional. All text is in English."""

FIGMA_FILE = "https://www.figma.com/design/GZRi3cvtWVfu0MTxPvPEcY/Design-System"

P = lambda name, type_, default, required, desc: dict(name=name, type=type_, default=default, required=required, desc=desc)

SPECS = [
    # ------------------------------------------------------------------ ATOMS
    dict(
        name="Button", category="atom", status="stable", figma="8:425",
        purpose="Triggers an action in the current view.",
        when=["Submit a form, confirm or cancel a decision.", "Start a flow (Send new submission, View & Download).", "Only one primary variant per view: the main action."],
        when_not=["To navigate to another URL: use a link (`as=\"a\"`) or `ListItem` type=navigation.", "To toggle a setting: use `Switch`.", "For selectable filters: use `TagChip`."],
        anatomy=["Container (background, border, radius `button.radius`)", "Optional leading icon (`Icon`)", "Label (`typography.button` style)", "Optional trailing icon (`Icon`)"],
        props=[P("children", "ReactNode", "—", True, "Visible button text. Verb + object: 'Send request'."),
               P("variant", "'primary' | 'secondary' | 'ghost' | 'danger'", "'primary'", False, "Visual hierarchy of the action."),
               P("size", "'small' | 'medium' | 'large'", "'medium'", False, "Height 32 / 44 / 52 px."),
               P("leadingIcon", "IconName", "—", False, "Icon before the text."),
               P("trailingIcon", "IconName", "—", False, "Icon after the text."),
               P("isDisabled", "boolean", "false", False, "Disables the button (aria-disabled)."),
               P("isLoading", "boolean", "false", False, "Replaces the leading icon with a Spinner and blocks clicks."),
               P("isFullWidth", "boolean", "false", False, "Fills the container width (forms)."),
               P("type", "'button' | 'submit' | 'reset'", "'button'", False, "HTML type."),
               P("onPress", "() => void", "—", False, "Action on press (click, Enter, Space).")],
        variants={"variant": ["primary", "secondary", "ghost", "danger"], "size": ["small", "medium", "large"]},
        states=["default", "hover", "pressed", "focus", "disabled", "loading"],
        tokens=["button.primary.*", "button.secondary.*", "button.ghost.*", "button.danger.*", "button.disabled.*", "button.radius", "button.gap", "button.padding-horizontal.*", "button.typography", "elevation.focus", "size.layout.control-height*"],
        interaction=["Hover and pressed change the background with `motion.transition-fast`.", "Enter and Space trigger `onPress`.", "While loading the width does not change and `aria-busy=true`."],
        a11y=["Native `<button>` element; if it navigates, an `<a>` with the same style.", "Visible focus: 2px `color.border.focus` outline outside the button.", "Icon-only buttons need an `aria-label` and a `Tooltip`.", "Primary keeps the Coach Platform CTA gradient (ocean 600→400, #3b8eaa → #5aaec8). White text on it is 3.7–2.5:1, below WCAG AA 4.5:1: a known exception chosen by product design. Secondary, ghost and danger meet 4.5:1.", "Disabled uses `aria-disabled` so screen readers can still find it."],
        composition=["At most one primary per view or per Modal.", "In a group, the main action goes on the right (Modal) or on top at full width (FormSection).", "Do not nest interactive elements inside."],
        antipatterns=["Two primary buttons in the same view.", "Changing colors with ad-hoc styles instead of `variant`.", "Using `ghost` for destructive actions.", "Generic text ('Click here', 'OK')."],
        deps=["Icon", "Spinner"],
        example='<Button variant="primary" leadingIcon="eye" onPress={openReview}>View & Download</Button>',
        examples_bad='<Button style={{ background: "#3b8eaa" }}>OK</Button>',
    ),
    dict(
        name="Icon", category="atom", status="stable", figma="7:6",
        purpose="Shows a line pictogram from the Alora icon set.",
        when=["Reinforce the meaning of a text (buttons, tags, navigation).", "Icon-only buttons when space is tight and the meaning is universal (close, search)."],
        when_not=["As the only way to communicate a state: add text.", "For illustrations or logos: use images or the Sidebar logo."],
        anatomy=["24×24 box", "2px stroke with round caps (Lucide style)"],
        props=[P("name", "IconName", "—", True, "home, list, user, users, calendar, play-circle, bell, eye, clock, check, close, chevron-right, chevron-left, search, info, plus, upload, log-in, log-out, edit, repeat, warning, check-circle, star, trending-up, mail, lock, trash, video."),
               P("size", "'xs' | 'sm' | 'md' | 'lg' | 'xl'", "'lg'", False, "12 / 16 / 20 / 24 / 32 px (`size.icon.*`)."),
               P("tone", "'primary' | 'secondary' | 'brand' | 'inherit'", "'inherit'", False, "Color `color.icon.*`; inherit uses currentColor."),
               P("label", "string", "—", False, "When set, the icon is meaningful (`role=img` + `aria-label`). Otherwise `aria-hidden`.")],
        variants={"size": ["xs", "sm", "md", "lg", "xl"], "tone": ["primary", "secondary", "brand", "inherit"]},
        states=["—"],
        tokens=["color.icon.primary", "color.icon.secondary", "color.icon.brand", "size.icon.*"],
        interaction=["Not interactive on its own."],
        a11y=["Decorative by default (`aria-hidden=true`).", "With `label` it becomes `role=img`.", "Contrast ≥ 3:1 against the background when it carries information."],
        composition=["Inside Button, Tag, NavigationItem, Notification, Input.", "The parent component decides the color (`tone=inherit`)."],
        antipatterns=["Icons from other libraries mixed with the set.", "Changing the stroke width.", "An icon with no text or aria-label on a control."],
        deps=[],
        example='<Icon name="clock" size="sm" tone="inherit" />',
        examples_bad='<img src="clock.png" />',
    ),
    dict(
        name="Label", category="atom", status="stable", figma="9:11",
        purpose="Names a form control.",
        when=["Above Input or Textarea, or to the right of Checkbox, Radio and Switch."],
        when_not=["As a section title: use Heading.", "As helper text: use Text inside FormField."],
        anatomy=["Text (`typography.label`)", "Optional required mark (*)"],
        props=[P("children", "ReactNode", "—", True, "Field name."),
               P("htmlFor", "string", "—", True, "id of the associated control."),
               P("isRequired", "boolean", "false", False, "Adds * and requires aria-required on the control."),
               P("isDisabled", "boolean", "false", False, "Dims the label (`color.text.disabled`).")],
        variants={}, states=["default", "disabled"],
        tokens=["typography.label", "color.text.primary", "color.text.disabled", "color.feedback.danger.foreground"],
        interaction=["Clicking the label focuses or toggles the control."],
        a11y=["Native `<label for>`.", "The asterisk is decorative (`aria-hidden`); required state is conveyed with `aria-required`."],
        composition=["Only inside FormField or next to Checkbox / Radio / Switch."],
        antipatterns=["Using the placeholder as the label.", "Typing labels in uppercase: the style already defines the typography."],
        deps=[],
        example='<Label htmlFor="email" isRequired>Email</Label>',
        examples_bad='<span style={{ fontWeight: 600 }}>Email</span>',
    ),
    dict(
        name="Text", category="atom", status="stable", figma="9:65",
        purpose="Shows reading text and metadata with a type role and a semantic tone.",
        when=["Paragraphs, descriptions, metadata, dates and overlines."],
        when_not=["Titles: use Heading.", "Form labels: use Label."],
        anatomy=["Text"],
        props=[P("children", "ReactNode", "—", True, "Content."),
               P("role", "'body-large' | 'body-medium' | 'body-small' | 'caption' | 'overline'", "'body-medium'", False, "Type style (`typography.*`)."),
               P("tone", "'primary' | 'secondary' | 'tertiary' | 'brand' | 'danger'", "'primary'", False, "Semantic color."),
               P("as", "'p' | 'span' | 'div' | 'dd' | 'dt'", "'p'", False, "HTML element.")],
        variants={"role": ["body-large", "body-medium", "body-small", "caption", "overline"], "tone": ["primary", "secondary", "tertiary", "brand", "danger"]},
        states=["—"],
        tokens=["typography.body-*", "typography.caption", "typography.overline", "color.text.*", "color.feedback.danger.foreground"],
        interaction=["Not interactive."],
        a11y=["`tertiary` meets 4.5:1 on surface-raised, but is not used for critical information.", "Acronyms in `overline` are typed in uppercase in the content; do not rely on text-transform for them."],
        composition=["Free to use inside molecules and organisms."],
        antipatterns=["Combining size and weight by hand instead of `role`.", "Using `brand` widely for text that is not a link."],
        deps=[],
        example='<Text role="body-small" tone="tertiary">Submitted 31 ago 2026, 18:01</Text>',
        examples_bad='<p style={{ fontSize: 12, color: "#4d6e87" }}>Submitted…</p>',
    ),
    dict(
        name="Heading", category="atom", status="stable", figma="9:77",
        purpose="Titles a view, section or card while respecting the document hierarchy.",
        when=["View greeting (display, h1).", "Section titles (medium, h2) and card titles (small, h3)."],
        when_not=["To emphasize text within a paragraph: use Text."],
        anatomy=["Text (`typography.display` or `typography.heading-*`)"],
        props=[P("children", "ReactNode", "—", True, "Title text."),
               P("level", "'display' | 'large' | 'medium' | 'small'", "'medium'", False, "Visual style."),
               P("as", "'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6'", "from level", False, "Semantic level; do not skip levels.")],
        variants={"level": ["display", "large", "medium", "small"]}, states=["—"],
        tokens=["typography.display", "typography.heading-large", "typography.heading-medium", "typography.heading-small", "color.text.primary"],
        interaction=["Not interactive."],
        a11y=["Only one h1 per view.", "Level order reflects structure, not size."],
        composition=["PageHeader uses display; DataList uses medium; SubmissionCard uses small."],
        antipatterns=["Using Heading for bold text that is not a title.", "Jumping from h1 to h4."],
        deps=[],
        example='<Heading level="display" as="h1">Welcome, Alejandro</Heading>',
        examples_bad='<div className="big-bold">Welcome</div>',
    ),
    dict(
        name="Input", category="atom", status="stable", figma="9:161",
        purpose="Collects one line of text.",
        when=["Email, password, name, search (through SearchField)."],
        when_not=["Long text: use Textarea.", "Fixed options: use Radio or a Select (planned)."],
        anatomy=["Container (background `input.background`, border `input.border.*`, radius `input.radius`)", "Optional leading icon", "Value or placeholder", "Optional trailing icon (show password)"],
        props=[P("id", "string", "—", True, "Links the Label and messages."),
               P("value", "string", "—", False, "Controlled value."),
               P("placeholder", "string", "—", False, "Format example; never replaces the Label."),
               P("type", "'text' | 'email' | 'password' | 'search' | 'tel'", "'text'", False, "HTML type."),
               P("leadingIcon", "IconName", "—", False, "Icon before the value."),
               P("trailingIcon", "IconName", "—", False, "Icon or action after the value."),
               P("hasError", "boolean", "false", False, "Error border and `aria-invalid`."),
               P("isDisabled", "boolean", "false", False, "Disabled."),
               P("onChange", "(value: string) => void", "—", False, "Value change.")],
        variants={}, states=["default", "hover", "focus", "error", "disabled", "filled"],
        tokens=["input.background", "input.foreground", "input.placeholder", "input.border.default", "input.border.hover", "input.border.focus", "input.border.error", "input.radius", "input.padding-horizontal", "input.typography", "size.layout.control-height", "size.border.focus"],
        interaction=["Focus: 2px `input.border.focus` border.", "Error: 2px `input.border.error` border; FormField renders the message."],
        a11y=["Always with an associated Label (FormField guarantees it).", "`aria-invalid` and `aria-describedby` pointing to helper and error text.", "Correct `autocomplete` (email, current-password)."],
        composition=["Use inside FormField. Outside a form, only through SearchField."],
        antipatterns=["Placeholder as the only label.", "Red borders with no error message."],
        deps=["Icon"],
        example='<Input id="email" type="email" value={email} onChange={setEmail} />',
        examples_bad='<input style={{ border: "1px solid red" }} placeholder="Email" />',
    ),
    dict(
        name="Textarea", category="atom", status="stable", figma="9:177",
        purpose="Collects multiple lines of text.",
        when=["Surfer note to the coach, reason for changing coach."],
        when_not=["Single-line values: use Input."],
        anatomy=["Container (`input.*` tokens)", "Value or placeholder", "Optional counter"],
        props=[P("id", "string", "—", True, "Links the Label."),
               P("value", "string", "—", False, "Controlled value."),
               P("maxLength", "number", "—", False, "Shows an 'n / max' counter."),
               P("rows", "number", "4", False, "Initial height."),
               P("hasError", "boolean", "false", False, "Error state."),
               P("isDisabled", "boolean", "false", False, "Disabled."),
               P("onChange", "(value: string) => void", "—", False, "Value change.")],
        variants={}, states=["default", "focus", "error", "disabled"],
        tokens=["input.*", "typography.body-medium", "typography.caption", "color.text.tertiary"],
        interaction=["Grows with the content up to 8 rows, then scrolls."],
        a11y=["Counter linked with `aria-describedby` and announced when the limit is reached."],
        composition=["Inside FormField or the Modal Content slot."],
        antipatterns=["Using it for a single short value."],
        deps=[],
        example='<Textarea id="note" maxLength={280} value={note} onChange={setNote} />',
        examples_bad='<textarea style={{ height: 112 }} />',
    ),
    dict(
        name="Checkbox", category="atom", status="stable", figma="12:44",
        purpose="Lets the user check one or more independent options.",
        when=["Accept terms, 'Remember me', select several items."],
        when_not=["One option among several: Radio.", "Setting with immediate effect: Switch."],
        anatomy=["18×18 box (`checkbox.radius`)", "Check mark or dash (indeterminate)", "Label"],
        props=[P("label", "ReactNode", "—", True, "Visible text."),
               P("isChecked", "boolean | 'indeterminate'", "false", False, "State."),
               P("isDisabled", "boolean", "false", False, "Disabled."),
               P("onChange", "(checked: boolean) => void", "—", False, "Change.")],
        variants={"checked": ["false", "true", "indeterminate"]}, states=["default", "focus", "disabled"],
        tokens=["checkbox.border", "checkbox.background-checked", "checkbox.foreground-checked", "checkbox.radius", "color.border.focus"],
        interaction=["Clicking the box or label toggles it.", "Space toggles it when focused."],
        a11y=["Native `<input type=checkbox>`.", "Indeterminate uses `aria-checked=mixed`.", "Clickable area ≥ 24×24 including the label."],
        composition=["Groups go inside a `<fieldset>` with a `<legend>`."],
        antipatterns=["A checkbox that triggers an immediate action.", "No visible label."],
        deps=["Icon", "Label"],
        example='<Checkbox label="Remember me" isChecked={remember} onChange={setRemember} />',
        examples_bad='<div onClick={toggle} className="box" />',
    ),
    dict(
        name="Radio", category="atom", status="stable", figma="12:71",
        purpose="Lets the user pick one option within a group.",
        when=["2–5 visible mutually exclusive options (Regular/Goofy stance, level)."],
        when_not=["More than 5 options: Select (planned).", "Multiple choices: Checkbox."],
        anatomy=["18×18 circle", "Inner dot when selected", "Label"],
        props=[P("label", "ReactNode", "—", True, "Visible text."),
               P("value", "string", "—", True, "Option value."),
               P("name", "string", "—", True, "Group name."),
               P("isSelected", "boolean", "false", False, "Selected."),
               P("isDisabled", "boolean", "false", False, "Disabled.")],
        variants={"selected": ["false", "true"]}, states=["default", "focus", "disabled"],
        tokens=["radio.border", "radio.border-checked", "radio.dot", "color.border.focus"],
        interaction=["Arrow keys move the selection within the group."],
        a11y=["`<input type=radio>` inside a `<fieldset>` with a `<legend>`, or a named `role=radiogroup`."],
        composition=["Always in a group of at least 2."],
        antipatterns=["A lone radio button.", "A group with no default option when the value is required."],
        deps=["Label"],
        example='<Radio name="stance" value="goofy" label="Goofy" isSelected={stance === "goofy"} />',
        examples_bad='<Radio label="Accept terms" />',
    ),
    dict(
        name="Switch", category="atom", status="stable", figma="12:91",
        purpose="Turns a setting on or off with immediate effect.",
        when=["Preferences saved instantly (notifications)."],
        when_not=["When the change needs a Save button: Checkbox."],
        anatomy=["36×20 track (`switch.radius`)", "16×16 thumb", "Label"],
        props=[P("label", "ReactNode", "—", True, "Visible text."),
               P("isOn", "boolean", "false", False, "State."),
               P("isDisabled", "boolean", "false", False, "Disabled."),
               P("onChange", "(on: boolean) => void", "—", False, "Change.")],
        variants={"on": ["false", "true"]}, states=["default", "disabled"],
        tokens=["switch.track-off", "switch.track-on", "switch.thumb", "switch.radius", "color.border.default"],
        interaction=["The thumb slides with `motion.transition-base`."],
        a11y=["`role=switch` + `aria-checked`.", "State does not rely on color alone: the thumb position changes."],
        composition=["Settings lists, one per row."],
        antipatterns=["A Switch inside a form with a Save button."],
        deps=["Label"],
        example='<Switch label="Email notifications" isOn={notify} onChange={setNotify} />',
        examples_bad='<Switch label="Accept terms" />',
    ),
    dict(
        name="Avatar", category="atom", status="stable", figma="12:119",
        purpose="Represents a person with their initials.",
        when=["Next to a surfer or coach name (lists, cards, header)."],
        when_not=["As the only identifier of a person: always show the name."],
        anatomy=["Circle (`avatar.radius`)", "Initials"],
        props=[P("name", "string", "—", True, "Full name; initials are derived from it."),
               P("size", "'small' | 'medium' | 'large'", "'medium'", False, "24 / 32 / 64 px."),
               P("tone", "'brand' | 'elite' | 'progression' | 'neutral'", "'brand'", False, "Background color; plan tones go with a plan Badge.")],
        variants={"size": ["small", "medium", "large"], "tone": ["brand", "elite", "progression", "neutral"]}, states=["—"],
        tokens=["avatar.background", "avatar.foreground", "avatar.radius", "color.plan.*.foreground", "color.text.inverse"],
        interaction=["Not interactive; if it opens the profile, wrap it in a link with the name."],
        a11y=["Initials are `aria-hidden`; the visible name next to it gives context."],
        composition=["ListItem type=person, SubmissionCard, PageHeader."],
        antipatterns=["Communicating the plan only through the avatar color."],
        deps=[],
        example='<Avatar name="Khata Kraiwan" tone="elite" />',
        examples_bad='<div className="circle" style={{ background: "#d97706" }}>K</div>',
    ),
    dict(
        name="Badge", category="atom", status="stable", figma="12:139",
        purpose="Non-interactive label that shows a status or a plan.",
        when=["Submission status (Pending, In review, Review ready, Overdue).", "Surfer plan (Pay as you go, Elite, Progression)."],
        when_not=["Information with an icon or a time: Tag.", "Selectable or removable items: TagChip."],
        anatomy=["Container (`badge.radius`, padding `badge.padding-*`)", "Uppercase text (`typography.overline`)"],
        props=[P("children", "string", "—", True, "Status text."),
               P("tone", "'pending' | 'in-review' | 'review-ready' | 'overdue' | 'neutral' | 'plan-pay-as-you-go' | 'plan-elite' | 'plan-progression'", "'neutral'", False, "Semantic tone.")],
        variants={"tone": ["pending", "in-review", "review-ready", "overdue", "neutral", "plan-pay-as-you-go", "plan-elite", "plan-progression"]}, states=["—"],
        tokens=["badge.radius", "badge.padding-horizontal", "badge.padding-vertical", "badge.typography", "color.status.*", "color.plan.*", "color.feedback.neutral.*"],
        interaction=["Not interactive."],
        a11y=["The text names the state; color only reinforces it.", "Contrast ≥ 4.5:1 in every tone."],
        composition=["SubmissionCard (status and plan), future Sidebar counters."],
        antipatterns=["A clickable Badge.", "Inventing tones outside the list."],
        deps=[],
        example='<Badge tone="in-review">In review</Badge>',
        examples_bad='<span style={{ color: "#f5c53a" }}>Pending</span>',
    ),
    dict(
        name="Tag", category="atom", status="stable", figma="12:167",
        purpose="Informational pill with an optional icon.",
        when=["Time left on a review, highlighted plan, context (Surf park)."],
        when_not=["Short states without an icon: Badge.", "Selectable or removable items: TagChip."],
        anatomy=["Pill container (`tag.radius`)", "Optional icon", "Text (`typography.body-small`)"],
        props=[P("children", "ReactNode", "—", True, "Text."),
               P("tone", "'brand' | 'highlight' | 'warning' | 'danger' | 'neutral'", "'brand'", False, "Semantic tone."),
               P("icon", "IconName", "—", False, "Leading icon.")],
        variants={"tone": ["brand", "highlight", "warning", "danger", "neutral"]}, states=["—"],
        tokens=["tag.background", "tag.foreground", "tag.border", "tag.radius", "tag.padding-horizontal", "color.background.highlight-subtle", "color.text.highlight", "color.feedback.*"],
        interaction=["Not interactive."],
        a11y=["If the Tag conveys urgency (warning/danger), the text says so ('1h 9m left', 'Overdue')."],
        composition=["SubmissionCard (deadline), PageHeader (plan, notifications)."],
        antipatterns=["Using Tag as a button."],
        deps=["Icon"],
        example='<Tag tone="warning" icon="clock">1h 9m left</Tag>',
        examples_bad='<Tag onClick={…}>Filter</Tag>',
    ),
    dict(
        name="Spinner", category="atom", status="stable", figma="12:180",
        purpose="Indicates a wait of unknown duration.",
        when=["Video upload, review submission, loading the queue."],
        when_not=["Measurable progress: progress bar (planned).", "Loading a whole view: skeletons (planned)."],
        anatomy=["Circular track (`spinner.track`)", "Animated arc (`spinner.indicator`)"],
        props=[P("size", "'small' | 'medium' | 'large'", "'medium'", False, "16 / 24 / 32 px."),
               P("label", "string", "'Loading'", False, "Text for screen readers.")],
        variants={"size": ["small", "medium", "large"]}, states=["—"],
        tokens=["spinner.track", "spinner.indicator", "size.border.focus", "motion.loop-duration"],
        interaction=["Rotates continuously; with `prefers-reduced-motion` the animation stops."],
        a11y=["`role=status` with `aria-label`.", "Respects `prefers-reduced-motion`."],
        composition=["Inside Button (isLoading) or centered in a loading EmptyState."],
        antipatterns=["Several spinners at once in one view."],
        deps=[],
        example='<Spinner size="small" label="Uploading video" />',
        examples_bad='<img src="loader.gif" />',
    ),
    dict(
        name="Divider", category="atom", status="stable", figma="12:186",
        purpose="Separates groups of content.",
        when=["Between the stats block and the submissions list; between list rows."],
        when_not=["To create space: use `size.space.*` tokens."],
        anatomy=["1px line (`divider.color`)"],
        props=[P("orientation", "'horizontal' | 'vertical'", "'horizontal'", False, "Direction."),
               P("isDecorative", "boolean", "true", False, "When false, `role=separator`.")],
        variants={"orientation": ["horizontal", "vertical"]}, states=["—"],
        tokens=["divider.color", "size.border.default"],
        interaction=["Not interactive."],
        a11y=["Decorative by default (`aria-hidden`)."],
        composition=["Free to use."],
        antipatterns=["Hand-drawn borders in other colors."],
        deps=[],
        example='<Divider />',
        examples_bad='<hr style={{ borderColor: "#333" }} />',
    ),
    dict(
        name="Tooltip", category="atom", status="beta", figma="12:200",
        purpose="Briefly describes a control on hover or focus.",
        when=["Icon-only buttons, abbreviations."],
        when_not=["Essential information or actions: use visible text or Notification."],
        anatomy=["Bubble (`tooltip.background`, `tooltip.radius`)", "Arrow", "Text (`typography.body-small`)"],
        props=[P("content", "string", "—", True, "Short text (≤ 60 characters)."),
               P("placement", "'top' | 'bottom'", "'top'", False, "Placement."),
               P("children", "ReactElement", "—", True, "Focusable trigger element.")],
        variants={"placement": ["top", "bottom"]}, states=["hidden", "visible"],
        tokens=["tooltip.background", "tooltip.foreground", "tooltip.radius", "tooltip.padding", "layer.tooltip"],
        interaction=["Appears after 300ms of hover, or instantly on focus; Escape closes it."],
        a11y=["`role=tooltip` linked with `aria-describedby`.", "Does not disappear while the pointer is over it (WCAG 1.4.13)."],
        composition=["Wraps an icon-only Button."],
        antipatterns=["Tooltips containing links or buttons."],
        deps=[],
        example='<Tooltip content="Close"><Button variant="ghost" leadingIcon="close" aria-label="Close" /></Tooltip>',
        examples_bad='<Tooltip content="Your plan renews on 26 sept and you will be charged…">',
    ),
    # -------------------------------------------------------------- MOLECULES
    dict(
        name="FormField", category="molecule", status="stable", figma="13:54",
        purpose="Groups a field's Label, Input, helper text and error message.",
        when=["Any form field (log in, onboarding, profile)."],
        when_not=["Search: SearchField."],
        anatomy=["Label", "Input or Textarea", "Optional helper text", "Error message with icon"],
        props=[P("label", "string", "—", True, "Label text."),
               P("id", "string", "—", True, "Control id."),
               P("helperText", "string", "—", False, "Help below the field."),
               P("errorMessage", "string", "—", False, "When set, the field switches to the error state."),
               P("isRequired", "boolean", "false", False, "Required."),
               P("isDisabled", "boolean", "false", False, "Disabled."),
               P("children", "ReactElement<Input | Textarea>", "—", True, "The control.")],
        variants={}, states=["default", "error", "disabled"],
        tokens=["size.space.small", "typography.body-small", "color.text.tertiary", "color.feedback.danger.foreground"],
        interaction=["The error appears on blur or on submit, not while typing."],
        a11y=["Connects `aria-describedby` to the helper and error text.", "The error is announced with `role=alert` the first time."],
        composition=["Inside FormSection or the Modal Content slot."],
        antipatterns=["Showing helper text and an error at the same time.", "Error messages that do not say how to fix the problem."],
        deps=["Label", "Input", "Textarea", "Text", "Icon"],
        example='<FormField id="email" label="Email" errorMessage={error}>\n  <Input id="email" type="email" />\n</FormField>',
        examples_bad='<Label>Email</Label><Input /><span className="red">Error</span>',
    ),
    dict(
        name="SearchField", category="molecule", status="stable", figma="13:92",
        purpose="Search field with an icon and a clear button.",
        when=["Search surfers, clips or spots in long lists."],
        when_not=["Filters with a fixed set of values: TagChip."],
        anatomy=["Input with a search icon", "Clear button (visible when there is text)"],
        props=[P("value", "string", "—", True, "Search text."),
               P("onChange", "(value: string) => void", "—", True, "Change."),
               P("placeholder", "string", "'Search'", False, "What is being searched: 'Search surfers'."),
               P("onClear", "() => void", "—", False, "Clears and returns focus.")],
        variants={"filled": ["false", "true"]}, states=["default", "focus"],
        tokens=["input.*", "color.icon.secondary"],
        interaction=["Escape clears the text.", "Results are filtered with a 200ms debounce."],
        a11y=["`role=search` container; `type=search` Input with a hidden label.", "The clear button has `aria-label=\"Clear search\"`."],
        composition=["Above lists (Surfers)."],
        antipatterns=["Search without an accessible label."],
        deps=["Input", "Icon", "Button"],
        example='<SearchField value={q} onChange={setQ} placeholder="Search surfers" />',
        examples_bad='<Input placeholder="Search…" />',
    ),
    dict(
        name="ListItem", category="molecule", status="stable", figma="13:120",
        purpose="List row with three formats: person, definition or navigation.",
        when=["List of surfers (person).", "Account details (definition).", "Legal links (navigation)."],
        when_not=["Rich content with several actions: SubmissionCard."],
        anatomy=["person: Avatar + title + description + action", "definition: label + value + optional action", "navigation: title + chevron"],
        props=[P("type", "'person' | 'definition' | 'navigation'", "'definition'", False, "Format."),
               P("title", "string", "—", True, "Title or label."),
               P("description", "string", "—", False, "Description (person) or value (definition)."),
               P("avatarName", "string", "—", False, "person only."),
               P("action", "{ label: string; onPress: () => void; tone?: 'default' | 'danger' }", "—", False, "Action on the right."),
               P("href", "string", "—", False, "navigation only: destination."),
               P("hasDivider", "boolean", "true", False, "Bottom divider.")],
        variants={"type": ["person", "definition", "navigation"]}, states=["default", "hover (navigation)"],
        tokens=["size.space.large", "size.space.medium", "divider.color", "typography.overline", "typography.body-small", "typography.heading-small"],
        interaction=["navigation: the whole row is clickable."],
        a11y=["Lists use `<ul>`; definition rows use `<dl>` with `<dt>`/`<dd>`."],
        composition=["DataList, surfer lists."],
        antipatterns=["Mixing types within the same list."],
        deps=["Avatar", "Heading", "Text", "Button", "Icon", "Divider"],
        example='<ListItem type="definition" title="PLAN RENEWS" description="26 sept 2026" action={{ label: "Cancel your plan", tone: "danger", onPress: openCancel }} />',
        examples_bad='<div className="row">…</div>',
    ),
    dict(
        name="TagChip", category="molecule", status="beta", figma="13:139",
        purpose="Selectable or removable chip.",
        when=["Filters (level, wave type), labels the user adds or removes."],
        when_not=["Static information: Tag or Badge."],
        anatomy=["Pill container", "Label", "Optional remove button"],
        props=[P("label", "string", "—", True, "Text."),
               P("isSelected", "boolean", "false", False, "Selected."),
               P("onToggle", "() => void", "—", False, "Selection."),
               P("onRemove", "() => void", "—", False, "Shows a remove button.")],
        variants={}, states=["default", "hover", "selected"],
        tokens=["tag.radius", "tag.padding-horizontal", "color.action.secondary.*", "color.background.brand-subtle", "color.border.brand", "color.text.brand"],
        interaction=["Clicking toggles; the remove button does not toggle."],
        a11y=["`<button aria-pressed>`; remove is a separate button with `aria-label=\"Remove {label}\"`."],
        composition=["Horizontal groups that wrap, with a `size.space.small` gap."],
        antipatterns=["Using TagChip for system states."],
        deps=["Text", "Icon"],
        example='<TagChip label="Advanced" isSelected onToggle={toggle} onRemove={remove} />',
        examples_bad='<Badge onClick={toggle}>Advanced</Badge>',
    ),
    dict(
        name="Stat", category="molecule", status="stable", figma="13:154",
        purpose="Shows a metric with its label and an optional trend.",
        when=["Queue summary (Pending, Reviewed) and plan summary (Cycle submissions, Renews)."],
        when_not=["Time series: chart (planned)."],
        anatomy=["Label", "Value (`typography.metric`)", "Optional trend (icon + text)"],
        props=[P("label", "string", "—", True, "What is measured."),
               P("value", "string | number", "—", True, "Formatted value."),
               P("trend", "{ direction: 'up' | 'down'; label: string }", "—", False, "Change.")],
        variants={"trend": ["none", "up"]}, states=["—"],
        tokens=["stat.background", "stat.label", "stat.value", "card.radius", "size.space.xl", "typography.metric", "color.feedback.success.foreground"],
        interaction=["Not interactive."],
        a11y=["Label and value in the same `<div role=group>` with `aria-label`.", "The trend is read as text."],
        composition=["Grid of stats that wraps at `size.layout.stat-min-width`."],
        antipatterns=["Trend shown only with color."],
        deps=["Text", "Icon"],
        example='<Stat label="Pending" value={3} />',
        examples_bad='<div className="stat"><b>3</b></div>',
    ),
    dict(
        name="Notification", category="molecule", status="stable", figma="13:209",
        purpose="Communicates a system message with a tone, an action and a dismiss button.",
        when=["Successful submission, approaching deadline, upload error, process info."],
        when_not=["Field errors: FormField.", "Blocking decisions: Modal."],
        anatomy=["Icon in a tinted container", "Title", "Description", "Optional action", "Optional dismiss"],
        props=[P("tone", "'info' | 'success' | 'warning' | 'danger'", "'info'", False, "Tone."),
               P("title", "string", "—", True, "Main message."),
               P("description", "string", "—", False, "Detail."),
               P("action", "{ label: string; onPress: () => void }", "—", False, "Action."),
               P("onDismiss", "() => void", "—", False, "Shows a dismiss button.")],
        variants={"tone": ["info", "success", "warning", "danger"]}, states=["visible", "dismissed"],
        tokens=["notification.background", "notification.border", "notification.radius", "color.feedback.*", "typography.heading-small", "typography.body-small"],
        interaction=["info/success may auto-dismiss after 6s; warning/danger never do."],
        a11y=["info/success use `role=status`; danger uses `role=alert`.", "Dismiss is a button with `aria-label=\"Dismiss\"`."],
        composition=["Stacked in the top-right corner (`layer.toast`) or inline above the content."],
        antipatterns=["More than 3 visible notifications.", "Error messages that disappear on their own."],
        deps=["Icon", "Heading", "Text", "Button"],
        example='<Notification tone="success" title="Submission sent" description="Your coach has 48h to review your clip." />',
        examples_bad='alert("Upload failed")',
    ),
    dict(
        name="Breadcrumb", category="molecule", status="beta", figma="13:210",
        purpose="Shows where the user is within a hierarchy.",
        when=["Detail views 3+ levels deep (Surfers › Surfer › Clip)."],
        when_not=["Top-level Sidebar views."],
        anatomy=["Links", "Chevron separators", "Current item"],
        props=[P("items", "Array<{ label: string; href?: string }>", "—", True, "The last item is the current page.")],
        variants={}, states=["—"],
        tokens=["color.text.brand", "color.text.primary", "color.icon.secondary", "typography.body-small", "size.space.small"],
        interaction=["Links navigate; the current item is not a link."],
        a11y=["`<nav aria-label=\"Breadcrumb\">` + `<ol>`; current item with `aria-current=page`."],
        composition=["Above PageHeader in detail views."],
        antipatterns=["Breadcrumb as a replacement for the Sidebar."],
        deps=["Text", "Icon"],
        example='<Breadcrumb items={[{ label: "Surfers", href: "/surfers" }, { label: "Alejandro García" }]} />',
        examples_bad='<p>Surfers / Alejandro</p>',
    ),
    dict(
        name="Pagination", category="molecule", status="beta", figma="13:221",
        purpose="Moves between pages of a long list.",
        when=["History with more than 20 reviews."],
        when_not=["Short lists or continuous feeds."],
        anatomy=["Previous", "Page status", "Next"],
        props=[P("page", "number", "—", True, "Current page (1-based)."),
               P("pageCount", "number", "—", True, "Total pages."),
               P("onPageChange", "(page: number) => void", "—", True, "Change.")],
        variants={}, states=["first", "middle", "last"],
        tokens=["button.*", "size.space.xs"],
        interaction=["Previous is disabled on the first page and Next on the last."],
        a11y=["`<nav aria-label=\"Pagination\">`; the page status is announced with `aria-live=polite`."],
        composition=["Below the list it paginates."],
        antipatterns=["Pagination with a single page."],
        deps=["Button", "Text"],
        example='<Pagination page={2} pageCount={8} onPageChange={setPage} />',
        examples_bad='<a>Next</a>',
    ),
    dict(
        name="NavigationItem", category="molecule", status="stable", figma="13:293",
        purpose="Main navigation entry with an icon and a label.",
        when=["Inside Sidebar."],
        when_not=["Actions: Button."],
        anatomy=["24px icon", "Label", "Bottom divider"],
        props=[P("label", "string", "—", True, "Destination."),
               P("icon", "IconName", "—", True, "Icon."),
               P("href", "string", "—", True, "URL."),
               P("isActive", "boolean", "false", False, "Current page.")],
        variants={}, states=["default", "hover", "active"],
        tokens=["navigation-item.*", "color.action.ghost.background-hover", "size.space.large"],
        interaction=["Hover tints the icon with the brand color."],
        a11y=["`<a>` with `aria-current=page` when active.", "Active state is shown by both text and icon color, not text color alone."],
        composition=["Only inside Sidebar."],
        antipatterns=["More than one active item at once."],
        deps=["Icon", "Text"],
        example='<NavigationItem label="Queue" icon="play-circle" href="/queue" isActive />',
        examples_bad='<div onClick={go}>Queue</div>',
    ),
    # -------------------------------------------------------------- ORGANISMS
    dict(
        name="Sidebar", category="organism", status="stable", figma="14:84",
        purpose="Fixed main navigation on desktop.",
        when=["Every authenticated Coach and Surfer view at ≥ 1024px."],
        when_not=["Mobile: bottom NavigationBar (planned)."],
        anatomy=["List of NavigationItem", "Logo at the bottom"],
        props=[P("product", "'coach' | 'surfer'", "—", True, "Sets the default items."),
               P("activeHref", "string", "—", True, "Active item."),
               P("items", "Array<NavigationItemProps>", "from product", False, "Overrides the items (max. 5).")],
        variants={"product": ["coach", "surfer"]}, states=["—"],
        tokens=["sidebar.background", "sidebar.width", "navigation-item.*"],
        interaction=["Stays fixed while scrolling (`layer.sticky`)."],
        a11y=["`<nav aria-label=\"Main\">`; a single `aria-current`."],
        composition=["Items slot (max. 5) + Logo.", "Not customizable: width, background, logo position."],
        antipatterns=["Adding actions (buttons) to the Sidebar."],
        deps=["NavigationItem"],
        example='<Sidebar product="coach" activeHref="/queue" />',
        examples_bad='<Sidebar style={{ width: 200 }} />',
    ),
    dict(
        name="PageHeader", category="organism", status="stable", figma="14:116",
        purpose="Header of each view with a title, subtitle and actions.",
        when=["First section of every view inside DashboardTemplate."],
        when_not=["Inner section titles: Heading medium."],
        anatomy=["Title (Heading, h1)", "Optional subtitle", "Actions slot (max. 2)"],
        props=[P("title", "string", "—", True, "Greeting or title."),
               P("subtitle", "string", "—", False, "Supporting text."),
               P("actions", "ReactNode", "—", False, "Tag, Avatar or Button (max. 2).")],
        variants={"context": ["coach", "surfer"]}, states=["—"],
        tokens=["typography.display", "color.text.brand", "size.space.small", "size.space.medium", "size.layout.content-width"],
        interaction=["Not interactive; its actions are."],
        a11y=["The only h1 in the view."],
        composition=["DashboardTemplate Header slot."],
        antipatterns=["More than two actions; use a menu."],
        deps=["Heading", "Text", "Tag", "Avatar"],
        example='<PageHeader title="Welcome, Alejandro" subtitle="Connect with your surfers" actions={<Avatar name="Coach" tone="elite" />} />',
        examples_bad='<h1 style={{ fontSize: 40 }}>Welcome</h1>',
    ),
    dict(
        name="SubmissionCard", category="organism", status="stable", figma="14:223",
        purpose="Summarizes a clip submitted for review and its main action.",
        when=["Coach queue, surfer submission list."],
        when_not=["A review already delivered in History: ReviewCard (planned)."],
        anatomy=["Header: Avatar + name + plan Badge + status Badge", "Clip title + date + metadata", "Surfer note (optional)", "Footer: deadline Tag + primary Button"],
        props=[P("surfer", "{ name: string; plan: 'pay-as-you-go' | 'elite' | 'progression' }", "—", True, "Who submitted it."),
               P("status", "'pending' | 'in-review' | 'review-ready' | 'overdue'", "—", True, "State."),
               P("clipTitle", "string", "—", True, "Maneuver."),
               P("submittedAt", "string", "—", True, "Formatted date."),
               P("meta", "string", "—", False, "Stance · level · spot."),
               P("note", "string", "—", False, "Message from the surfer."),
               P("deadline", "{ label: string; tone: 'on-track' | 'due-soon' | 'overdue' }", "—", True, "Deadline."),
               P("action", "{ label: string; icon?: IconName; onPress: () => void }", "—", True, "Main action.")],
        variants={"deadline": ["on-track", "due-soon", "overdue"]}, states=["—"],
        tokens=["card.background", "card.border", "card.radius", "card.padding", "card.gap", "color.background.surface-sunken", "size.layout.content-width"],
        interaction=["Only the button is interactive; the whole card is not clickable."],
        a11y=["`<article>` with the title as an h3 and `aria-labelledby`."],
        composition=["In a list: a column with a `size.space.large` gap.", "Customizable: text, tones and action. Not customizable: block order."],
        antipatterns=["Two primary buttons in the card.", "Hiding the status."],
        deps=["Avatar", "Heading", "Text", "Badge", "Tag", "Button"],
        example='<SubmissionCard surfer={{ name: "Khata Kraiwan", plan: "elite" }} status="in-review" clipTitle="Frontside snap" submittedAt="Aug 31, 2026, 18:01" deadline={{ label: "1h 9m left", tone: "due-soon" }} action={{ label: "View & Download", icon: "eye", onPress }} />',
        examples_bad='<Card><b>Frontside snap</b><button className="blue">View</button></Card>',
    ),
    dict(
        name="DataList", category="organism", status="stable", figma="14:224",
        purpose="Read-only data section with a title and definition rows.",
        when=["Account & Billing, Surf Profile, Legal."],
        when_not=["Comparable tabular data: DataTable (planned)."],
        anatomy=["Title with icon (Heading small)", "Card with ListItem type=definition or navigation"],
        props=[P("title", "string", "—", True, "Section title."),
               P("icon", "IconName", "—", False, "Title icon."),
               P("items", "Array<ListItemProps>", "—", True, "Rows.")],
        variants={}, states=["—"],
        tokens=["card.background", "card.border", "card.radius", "color.background.brand-subtle", "size.space.medium"],
        interaction=["Row actions are the only interactive elements."],
        a11y=["`<section aria-labelledby>` with an `<h2>` and `<dl>` rows."],
        composition=["Stack sections with a `size.space.xl` gap."],
        antipatterns=["Mixing in editable fields: use FormSection."],
        deps=["ListItem", "Heading", "Icon"],
        example='<DataList title="Account & Billing" icon="user" items={rows} />',
        examples_bad='<table>…</table>',
    ),
    dict(
        name="EmptyState", category="organism", status="stable", figma="14:277",
        purpose="Explains why an area is empty and offers the next action.",
        when=["Empty queue, empty history, no surfers."],
        when_not=["Errors: danger Notification."],
        anatomy=["Decorative icon", "Message", "Optional action (Button)"],
        props=[P("message", "string", "—", True, "Current state in the user's language."),
               P("icon", "IconName", "'info'", False, "Icon."),
               P("action", "{ label: string; icon?: IconName; onPress: () => void }", "—", False, "Next step.")],
        variants={"action": ["false", "true"]}, states=["—"],
        tokens=["card.background", "card.radius", "color.background.canvas", "color.text.tertiary", "size.space.xl"],
        interaction=["Only the action is interactive."],
        a11y=["Icon is `aria-hidden`; the message is real text."],
        composition=["Takes the place of the empty list."],
        antipatterns=["Messages that blame the user."],
        deps=["Icon", "Text", "Button"],
        example='<EmptyState message="No submissions waiting for review." />',
        examples_bad='<p>Nothing here</p>',
    ),
    dict(
        name="Modal", category="organism", status="stable", figma="14:348",
        purpose="Dialog for a decision or short task that interrupts the flow.",
        when=["Cancel a plan, request a coach change, confirm destructive actions."],
        when_not=["Non-blocking information: Notification.", "Long forms: a page of their own."],
        anatomy=["Title + close button", "Description", "Content slot", "Footer: secondary + primary action"],
        props=[P("isOpen", "boolean", "—", True, "Visibility."),
               P("title", "string", "—", True, "Title."),
               P("description", "string", "—", False, "Context."),
               P("tone", "'default' | 'danger'", "'default'", False, "danger uses a danger Button."),
               P("primaryAction", "{ label: string; onPress: () => void }", "—", True, "Main action."),
               P("secondaryAction", "{ label: string; onPress: () => void }", "—", False, "Cancel."),
               P("onClose", "() => void", "—", True, "Close (X, Escape, overlay)."),
               P("children", "ReactNode", "—", False, "Content slot.")],
        variants={"tone": ["default", "danger"]}, states=["open", "closed"],
        tokens=["modal.background", "modal.overlay", "modal.radius", "modal.padding", "modal.shadow", "layer.modal", "motion.transition-enter"],
        interaction=["Enters with `motion.transition-enter`; Escape and the overlay close it."],
        a11y=["Native `<dialog>` opened with `showModal()` and `aria-labelledby` pointing to the title.", "Focus is trapped and returns to the trigger on close.", "Initial focus goes to the first field, or to the secondary action when tone is danger."],
        composition=["The Content slot accepts FormField, Text and short lists."],
        antipatterns=["Chained modals.", "A modal with no way to close it."],
        deps=["Heading", "Text", "Button", "Icon", "FormField"],
        example='<Modal isOpen tone="danger" title="Cancel your plan?" primaryAction={{ label: "Cancel plan", onPress: cancel }} secondaryAction={{ label: "Keep my plan", onPress: close }} onClose={close} />',
        examples_bad='<div className="popup" style={{ zIndex: 9999 }}>…</div>',
    ),
    dict(
        name="FormSection", category="organism", status="stable", figma="14:349",
        purpose="Complete form with fields and actions.",
        when=["Log in, Create account, onboarding steps, edit profile."],
        when_not=["A single inline field: FormField."],
        anatomy=["Error summary (Notification) when there is more than one error", "Stacked FormFields", "Full-width primary action", "Optional ghost secondary action"],
        props=[P("onSubmit", "(event: FormEvent) => void", "—", True, "Submit."),
               P("children", "ReactNode", "—", True, "FormFields."),
               P("primaryAction", "{ label: string; icon?: IconName; isLoading?: boolean }", "—", True, "Submit."),
               P("secondaryAction", "{ label: string; onPress: () => void }", "—", False, "Alternative."),
               P("errorSummary", "string[]", "—", False, "Summary shown when there is more than one error.")],
        variants={}, states=["default", "submitting", "error"],
        tokens=["card.*", "size.layout.form-width", "size.space.large", "size.space.medium"],
        interaction=["Enter submits; the button shows its loading state while submitting."],
        a11y=["`<form noValidate>`; the error summary uses `role=alert` and focus goes to the first error."],
        composition=["AuthTemplate Form slot or the content column."],
        antipatterns=["Two primary actions.", "Validating while the user types."],
        deps=["FormField", "Button", "Notification"],
        example='<FormSection onSubmit={login} primaryAction={{ label: "Login", icon: "log-in" }} secondaryAction={{ label: "Create new account", onPress: goSignup }}>…</FormSection>',
        examples_bad='<form><input/><input/><button>Go</button></form>',
    ),
]
